import { useState, useCallback, useMemo, useEffect, useRef } from "react";
import { auth, db } from "./firebase";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, deleteUser, EmailAuthProvider, reauthenticateWithCredential } from "firebase/auth";
import { doc, setDoc, getDoc, deleteDoc } from "firebase/firestore";

const UI={en:{practice:"Practice",progress:"Progress",settings:"Settings",flipHint:"tap to flip · swipe ← →",hint:"Hint",gotIt:"Got it! →",still:"← Still learning",mastered:"Mastered",learning:"Learning",due:"Due",total:"Total",flips:"flips",done:"Target hit! ✨",example:"Example",play:"▶ Play",theme:"Appearance",autoPlay:"Auto-play sound",target:"Daily target",perDay:"/day",logout:"Log out",deleteAcc:"Delete account",deleteWarn:"Permanently deletes everything.",confirm:"Confirm delete",cancel:"Cancel",pw:"Password",mastery:"Overall mastery",week:"This week",levels:"Levels",cats:"Categories",pracDue:"Due cards",pracLearn:"Learning cards",pracAll:"Practice all",exit:"Exit",allDone:"All caught up!",back:"Back to categories",lang:"Interface language",shuffle:"Shuffle",replay:"Replay tutorial",new:"New",reviewing:"Reviewing",improving:"Improving",strong:"Strong",master:"Mastered",browseAll:"Browse all",dueNow:"due now"},de:{practice:"Übung",progress:"Fortschritt",settings:"Einstellungen",flipHint:"Tippen = umdrehen · Wischen ← →",hint:"Hinweis",gotIt:"Kann ich! →",still:"← Noch lernen",mastered:"Gemeistert",learning:"Am Lernen",due:"Fällig",total:"Gesamt",flips:"Karten",done:"Geschafft! ✨",example:"Beispiel",play:"▶",theme:"Aussehen",autoPlay:"Auto-Ton",target:"Tagesziel",perDay:"/Tag",logout:"Abmelden",deleteAcc:"Konto löschen",deleteWarn:"Löscht alles unwiderruflich.",confirm:"Endgültig löschen",cancel:"Abbrechen",pw:"Passwort",mastery:"Gesamtfortschritt",week:"Diese Woche",levels:"Stufen",cats:"Kategorien",pracDue:"Fällige Karten",pracLearn:"Lernkarten",pracAll:"Alle üben",exit:"Beenden",allDone:"Alles erledigt!",back:"Zurück",lang:"Sprache",shuffle:"Mischen",replay:"Tutorial wiederholen",new:"Neu",reviewing:"Wiederholung",improving:"Fortschritt",strong:"Sicher",master:"Gemeistert",browseAll:"Alle ansehen",dueNow:"fällig"}};
const CAT_DE={Numbers:"Zahlen","Family & People":"Familie","Body Parts":"Körperteile","Nature & Weather":"Natur & Wetter",Colors:"Farben","Food & Home":"Essen & Haus",Places:"Orte",Time:"Zeit",Emotions:"Gefühle",Adjectives:"Adjektive",Verbs:"Verben","Common Words":"Häufige Wörter",Sentences:"Sätze"};
const CAT_EMOJI={Numbers:"🔢","Family & People":"👨‍👩‍👧","Body Parts":"🫳","Nature & Weather":"🌧️",Colors:"🎨","Food & Home":"🏠",Places:"📍",Time:"⏰",Emotions:"💛",Adjectives:"✨",Verbs:"🏃","Common Words":"💬",Sentences:"🗣️"};

const ALL_CARDS=[
{id:1,front:"One (1)",frontDe:"Eins (1)",back:"एक (१)",tl:"Ek",pron:"ehk",cat:"Numbers",hint:"Starts with 'E' · 2 Devanagari letters · like 'egg' without the 'g'",hintDe:"Beginnt mit 'E' · 2 Buchstaben · wie 'Eck'",trick:"Eck = eins.",example:{hi:"एक सेब दो।",en:"Give one apple.",de:"Gib einen Apfel.",tl:"Ek seb do."}},
{id:2,front:"Two (2)",frontDe:"Zwei (2)",back:"दो (२)",tl:"Do",pron:"doe",cat:"Numbers",hint:"Starts with 'D' · 2 letters · rhymes with 'go'",hintDe:"Beginnt mit 'D' · 2 Buchstaben · Do-ppel = zwei",trick:"Do-ppel = zwei.",example:{hi:"दो केले लाओ।",en:"Bring two bananas.",de:"Bring zwei Bananen.",tl:"Do kele lao."}},
{id:3,front:"Three (3)",frontDe:"Drei (3)",back:"तीन (३)",tl:"Teen",pron:"teen",cat:"Numbers",hint:"Starts with 'T' · like English 'teen' · 3 letters",hintDe:"Beginnt mit 'T' · wie englisch 'teen' · 3 Buchstaben",trick:"Tee in drei Tassen.",example:{hi:"तीन दिन बाद।",en:"After three days.",de:"Nach drei Tagen.",tl:"Teen din baad."}},
{id:4,front:"Four (4)",frontDe:"Vier (4)",back:"चार (४)",tl:"Chaar",pron:"chaar",cat:"Numbers",hint:"Starts with 'Ch' · rhymes with 'car' · 3 letters",hintDe:"Beginnt mit 'Ch' · reimt sich auf 'Car'",trick:"Char = vier.",example:{hi:"चार लोग आए।",en:"Four people came.",de:"Vier Leute kamen.",tl:"Chaar log aaye."}},
{id:5,front:"Five (5)",frontDe:"Fünf (5)",back:"पाँच (५)",tl:"Paanch",pron:"paanch",cat:"Numbers",hint:"Starts with 'P' · nasal · like 'punch' · 4 letters",hintDe:"Beginnt mit 'P' · nasal · wie 'Punsch'",trick:"Punsch = fünf.",example:{hi:"पाँच मिनट रुको।",en:"Wait five minutes.",de:"Warte fünf Minuten.",tl:"Paanch minute ruko."}},
{id:6,front:"Six (6)",frontDe:"Sechs (6)",back:"छह (६)",tl:"Chhah",pron:"cheh",cat:"Numbers",hint:"Starts with 'Chh' (breathy) · 2 letters",hintDe:"Beginnt mit 'Chh' (gehaucht) · 2 Buchstaben",trick:"Schach — sechs.",example:{hi:"छह बजे आओ।",en:"Come at six.",de:"Komm um sechs.",tl:"Chhah baje aao."}},
{id:7,front:"Seven (7)",frontDe:"Sieben (7)",back:"सात (७)",tl:"Saat",pron:"saat",cat:"Numbers",hint:"Starts with 'S' · same as German 'Saat'! · 3 letters",hintDe:"Wie deutsches 'Saat'! · 3 Buchstaben",trick:"Saat = sieben.",example:{hi:"सात दिन एक हफ़्ता।",en:"Seven days = one week.",de:"Sieben Tage = eine Woche.",tl:"Saat din ek hafta."}},
{id:8,front:"Eight (8)",frontDe:"Acht (8)",back:"आठ (८)",tl:"Aath",pron:"aath",cat:"Numbers",hint:"Starts with 'Aa' · sounds very close to German 'Acht'!",hintDe:"Wie 'Acht' ohne 'ch'! · 2 Buchstaben",trick:"Fast wie Acht.",example:{hi:"आठ बजे नाश्ता।",en:"Breakfast at eight.",de:"Frühstück um acht.",tl:"Aath baje naashta."}},
{id:9,front:"Nine (9)",frontDe:"Neun (9)",back:"नौ (९)",tl:"Nau",pron:"now",cat:"Numbers",hint:"Starts with 'N' · sounds exactly like English 'now'! · 2 letters",hintDe:"Klingt wie 'neu'! · 2 Buchstaben",trick:"Nau = neu.",example:{hi:"नौ लोग हैं।",en:"Nine people.",de:"Neun Leute.",tl:"Nau log hain."}},
{id:10,front:"Ten (10)",frontDe:"Zehn (10)",back:"दस (१०)",tl:"Das",pron:"thus",cat:"Numbers",hint:"Starts with 'D' · same as German article 'das'! · 2 letters",hintDe:"Wie deutsches 'das'! · 2 Buchstaben",trick:"Das = zehn.",example:{hi:"दस मिनट और।",en:"Ten more minutes.",de:"Noch zehn Minuten.",tl:"Das minute aur."}},
{id:11,front:"Father",frontDe:"Vater",back:"पिता",tl:"Pitaa",pron:"pi-TAA",cat:"Family & People",hint:"Starts with 'P' · 3 letters · think flat bread...",hintDe:"Beginnt mit 'P' · 3 Buchstaben · Pita-Brot",trick:"Pita-Brot.",example:{hi:"मेरे पिता अंदर हैं।",en:"My father is inside.",de:"Mein Vater ist drinnen.",tl:"Mere pitaa andar hain."}},
{id:12,front:"Sister",frontDe:"Schwester",back:"बहन",tl:"Behen",pron:"beh-HEN",cat:"Family & People",hint:"Starts with 'B' · 3 letters · ends like a farm bird",hintDe:"Beginnt mit 'B' · 3 Buchstaben · endet wie 'hen'",trick:"Behen bahnt den Weg.",example:{hi:"मेरी बहन जवान है।",en:"My sister is young.",de:"Meine Schwester ist jung.",tl:"Meri behen javaan hai."}},
{id:13,front:"Relative",frontDe:"Verwandter",back:"रिश्तेदार",tl:"Rishtedaar",pron:"rish-tay-DAAR",cat:"Family & People",hint:"Starts with 'R' · long word · '-daar' = keeper",hintDe:"Beginnt mit 'R' · '-daar' = Hüter",trick:"Verwandte reichen die Hand.",example:{hi:"मेरे रिश्तेदार यहाँ हैं।",en:"My relatives are here.",de:"Meine Verwandten sind hier.",tl:"Mere rishtedaar yahan hain."}},
{id:14,front:"Neighbour",frontDe:"Nachbar",back:"पड़ोसी",tl:"Padosi",pron:"pa-ROH-see",cat:"Family & People",hint:"Starts with 'P' · 4 letters · ends in '-see'",hintDe:"Beginnt mit 'P' · 4 Buchstaben · Paradiso nebenan",trick:"Paradiso nebenan.",example:{hi:"हमारे पड़ोसी अच्छे हैं।",en:"Our neighbours are nice.",de:"Unsere Nachbarn sind nett.",tl:"Hamare padosi acche hain."}},
{id:15,front:"Guest",frontDe:"Gast",back:"मेहमान",tl:"Mehmaan",pron:"meh-MAAN",cat:"Family & People",hint:"Starts with 'M' · 4 letters · contains 'maan'",hintDe:"Beginnt mit 'M' · 4 Buchstaben · 'Mehr Mann' kommt",trick:"Mehr Mann kommt.",example:{hi:"मेहमान आ रहे हैं।",en:"Guests are coming.",de:"Gäste kommen.",tl:"Mehmaan aa rahe hain."}},
{id:16,front:"Man",frontDe:"Mann",back:"आदमी",tl:"Aadmi",pron:"AAD-mee",cat:"Family & People",hint:"Starts with 'Aa' · 4 letters · think first man in history",hintDe:"Beginnt mit 'Aa' · 4 Buchstaben · wie Adam",trick:"Wie Adam.",example:{hi:"अच्छा आदमी।",en:"Good man.",de:"Guter Mann.",tl:"Accha aadmi."}},
{id:17,front:"Anybody",frontDe:"Irgendjemand",back:"कोई भी",tl:"Koi bhi",pron:"KOY bhee",cat:"Family & People",hint:"Two words · first 'K' (like a fish!) · second = 'also'",hintDe:"Zwei Wörter · erstes mit 'K' · zweites = 'auch'",trick:"Koi Fisch im Teich.",example:{hi:"कोई भी आ सकता है।",en:"Anybody can come.",de:"Jeder kann kommen.",tl:"Koi bhi aa sakta hai."}},
{id:109,front:"Customer",frontDe:"Kunde",back:"ग्राहक",tl:"Graahak",pron:"GRAA-hak",cat:"Family & People",hint:"Starts with 'Gr' · 3 syllables · they grab deals",hintDe:"Beginnt mit 'Gr' · 3 Silben · greift nach Angeboten",trick:"Kunde greift zu.",example:{hi:"ग्राहक सही है।",en:"Customer is right.",de:"Der Kunde hat recht.",tl:"Graahak sahi hai."}},
{id:120,front:"Person",frontDe:"Person",back:"व्यक्ति / इंसान",tl:"Vyakti / Insaan",pron:"VYUK-ti / in-SAAN",cat:"Family & People",hint:"Two options · 'V' (formal, 4 letters) · 'I' (casual, 3 syllables, like 'in-sane')",hintDe:"Zwei Wörter · 'V' (formell) · 'I' (umgangssprachlich, wie 'in-sane')",trick:"Jeder Insaan ist einzigartig.",example:{hi:"हर इंसान अलग है।",en:"Every person is different.",de:"Jeder Mensch ist anders.",tl:"Har insaan alag hai."}},
{id:121,front:"Partner",frontDe:"Partner",back:"साथी",tl:"Saathi",pron:"SAA-thee",cat:"Family & People",hint:"Starts with 'S' · related to 'saath' (with) · 3 letters",hintDe:"Beginnt mit 'S' · verwandt mit 'saath' (mit)",trick:"Der Mit-Mensch.",example:{hi:"मेरा साथी ठीक है।",en:"My partner is fine.",de:"Meinem Partner geht's gut.",tl:"Mera saathi theek hai."}},
{id:131,front:"Family",frontDe:"Familie",back:"परिवार",tl:"Parivaar",pron:"pa-ri-VAAR",cat:"Family & People",hint:"Starts with 'P' · 4 letters · 'pari' + 'vaar'",hintDe:"Beginnt mit 'P' · 4 Buchstaben",trick:"Pari-ty kommt!",example:{hi:"मेरा परिवार बड़ा है।",en:"My family is big.",de:"Meine Familie ist groß.",tl:"Mera parivaar bada hai."}},
{id:18,front:"Hand",frontDe:"Hand",back:"हाथ",tl:"Haath",pron:"haath",cat:"Body Parts",hint:"Starts with 'H' · 2 letters · sounds like 'heart' with 'th'",hintDe:"Beginnt mit 'H' · 2 Buchstaben · wie 'hat'",trick:"Hand hat fünf Finger.",example:{hi:"हाथ साफ़ करो।",en:"Wash hands.",de:"Hände waschen.",tl:"Haath saaf karo."}},
{id:19,front:"Head",frontDe:"Kopf",back:"सिर",tl:"Sir",pron:"sir",cat:"Body Parts",hint:"Starts with 'S' · 2 letters · like English 'sir'!",hintDe:"Wie englisch 'sir'! · 2 Buchstaben",trick:"Sir = Kopf.",example:{hi:"सिर दुखता है।",en:"Head hurts.",de:"Kopf tut weh.",tl:"Sir dukhta hai."}},
{id:20,front:"Ear",frontDe:"Ohr",back:"कान",tl:"Kaan",pron:"kaan",cat:"Body Parts",hint:"Starts with 'K' · 2 letters · like a boat shape (Kahn)",hintDe:"Beginnt mit 'K' · 2 Buchstaben · wie 'Kahn'",trick:"Kahn-förmig.",example:{hi:"कान से सुनो।",en:"Listen with ears.",de:"Hör mit den Ohren.",tl:"Kaan se suno."}},
{id:98,front:"Foot",frontDe:"Fuß",back:"पैर",tl:"Pair",pron:"pair",cat:"Body Parts",hint:"Starts with 'P' · 2 letters · like English 'pair'!",hintDe:"Wie englisch 'pair'! · 2 Buchstaben",trick:"Ein Paar Füße.",example:{hi:"पैर मत हिलाओ।",en:"Don't shake foot.",de:"Wackel nicht mit dem Fuß.",tl:"Pair mat hilao."}},
{id:122,front:"Tongue",frontDe:"Zunge",back:"जीभ",tl:"Jeebh",pron:"JEEBH",cat:"Body Parts",hint:"Starts with 'J' · 2 letters · soft 'bh' at end",hintDe:"Beginnt mit 'J' · 2 Buchstaben",trick:"Zunge sagt 'ji'.",example:{hi:"जीभ मत दिखाओ।",en:"Don't show tongue.",de:"Zeig nicht die Zunge.",tl:"Jeebh mat dikhao."}},
{id:21,front:"Rain",frontDe:"Regen",back:"बारिश",tl:"Baarish",pron:"BAA-rish",cat:"Nature & Weather",hint:"Starts with 'B' · 4 letters · long 'aa' then '-rish'",hintDe:"Beginnt mit 'B' · 4 Buchstaben",trick:"Barsch bei Regen.",example:{hi:"बारिश हो रही है।",en:"It's raining.",de:"Es regnet.",tl:"Baarish ho rahi hai."}},
{id:22,front:"Wind",frontDe:"Wind",back:"हवा",tl:"Havaa",pron:"ha-VAA",cat:"Nature & Weather",hint:"Starts with 'H' · 3 letters · think tropical island...",hintDe:"Beginnt mit 'H' · 3 Buchstaben · Hawaii",trick:"Hawaii.",example:{hi:"हवा तेज़ है।",en:"Wind is strong.",de:"Der Wind ist stark.",tl:"Havaa tez hai."}},
{id:23,front:"River",frontDe:"Fluss",back:"नदी",tl:"Nadi",pron:"na-DEE",cat:"Nature & Weather",hint:"Starts with 'N' · 3 letters · girl's name Nadia comes from this",hintDe:"Beginnt mit 'N' · 3 Buchstaben · wie Nadia",trick:"Wie Nadia.",example:{hi:"नदी पास है।",en:"River is near.",de:"Der Fluss ist nah.",tl:"Nadi paas hai."}},
{id:24,front:"Ocean",frontDe:"Ozean",back:"समुद्र",tl:"Samudra",pron:"sa-MOOD-ra",cat:"Nature & Weather",hint:"Starts with 'S' · 4 letters · 3 syllables",hintDe:"Beginnt mit 'S' · 4 Buchstaben · 3 Silben",trick:"So viel Mud.",example:{hi:"समुद्र सुन्दर है।",en:"Ocean is beautiful.",de:"Der Ozean ist schön.",tl:"Samudra sundar hai."}},
{id:25,front:"Rose",frontDe:"Rose",back:"गुलाब",tl:"Gulaab",pron:"goo-LAAB",cat:"Nature & Weather",hint:"Starts with 'G' · 4 letters · a famous dessert has this name",hintDe:"Beginnt mit 'G' · 4 Buchstaben · Gulab Jamun!",trick:"Gulab Jamun.",example:{hi:"गुलाब लाल है।",en:"Rose is red.",de:"Die Rose ist rot.",tl:"Gulaab laal hai."}},
{id:26,front:"Weather",frontDe:"Wetter",back:"मौसम",tl:"Mausam",pron:"MOW-sam",cat:"Nature & Weather",hint:"Starts with 'M' · 3 letters · small animal at window",hintDe:"Beginnt mit 'M' · 3 Buchstaben · Maus am Fenster",trick:"Maus am Fenster.",example:{hi:"मौसम अच्छा है।",en:"Weather is nice.",de:"Wetter ist gut.",tl:"Mausam accha hai."}},
{id:27,front:"World",frontDe:"Welt",back:"दुनिया",tl:"Duniya",pron:"doo-nee-YAA",cat:"Nature & Weather",hint:"Starts with 'D' · 4 letters · 3 syllables · sandy hills",hintDe:"Beginnt mit 'D' · 4 Buchstaben · Dünen",trick:"Dünen.",example:{hi:"दुनिया बड़ी है।",en:"World is big.",de:"Die Welt ist groß.",tl:"Duniya badi hai."}},
{id:123,front:"Forest",frontDe:"Wald",back:"जंगल",tl:"Jungle",pron:"JUN-gul",cat:"Nature & Weather",hint:"Starts with 'J' · you already know this English word!",hintDe:"Beginnt mit 'J' · ist ins Englische gewandert!",trick:"Jungle = Hindi.",example:{hi:"जंगल में हवा ठंडी है।",en:"Wind is cold in forest.",de:"Im Wald ist der Wind kalt.",tl:"Jungle mein havaa thandi hai."}},
{id:135,front:"Cloud",frontDe:"Wolke",back:"बादल",tl:"Baadal",pron:"BAA-dul",cat:"Nature & Weather",hint:"Starts with 'B' · 3 letters · long 'aa'",hintDe:"Beginnt mit 'B' · 3 Buchstaben · langes 'aa'",trick:"Bad-all — alle baden in Wolken!",example:{hi:"बादल आ रहे हैं।",en:"Clouds are coming.",de:"Wolken kommen.",tl:"Baadal aa rahe hain."}},
{id:28,front:"Colour",frontDe:"Farbe",back:"रंग",tl:"Rang",pron:"rung",cat:"Colors",hint:"Starts with 'R' · just 2 letters! · like a ladder step",hintDe:"Beginnt mit 'R' · nur 2 Buchstaben! · Rang",trick:"Rang = Farbe.",example:{hi:"कौन सा रंग?",en:"Which colour?",de:"Welche Farbe?",tl:"Kaun sa rang?"}},
{id:29,front:"White",frontDe:"Weiß",back:"सफ़ेद",tl:"Safed",pron:"sa-FEYD",cat:"Colors",hint:"Starts with 'S' · 3 letters · starts like 'safe'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · wie 'safe'",trick:"Safe = weiß.",example:{hi:"दूध सफ़ेद है।",en:"Milk is white.",de:"Milch ist weiß.",tl:"Doodh safed hai."}},
{id:30,front:"Orange",frontDe:"Orange",back:"नारंगी",tl:"Naarangi",pron:"naa-RAN-gee",cat:"Colors",hint:"Starts with 'N' · 4 letters · contains 'rang' (colour)!",hintDe:"Beginnt mit 'N' · enthält 'Rang' (Farbe)!",trick:"Rang steckt drin.",example:{hi:"नारंगी सुन्दर है।",en:"Orange is beautiful.",de:"Orange ist schön.",tl:"Naarangi sundar hai."}},
{id:31,front:"Brown",frontDe:"Braun",back:"भूरा",tl:"Bhura",pron:"BHOO-raa",cat:"Colors",hint:"Starts with 'Bh' (breathy) · 3 letters",hintDe:"Beginnt mit 'Bh' · 3 Buchstaben · alte Burgen",trick:"Alte Burgen = braun.",example:{hi:"ज़मीन भूरी है।",en:"Ground is brown.",de:"Der Boden ist braun.",tl:"Zameen bhuri hai."}},
{id:32,front:"Sugar",frontDe:"Zucker",back:"चीनी",tl:"Cheeni",pron:"CHEE-nee",cat:"Food & Home",hint:"Starts with 'Ch' · 3 letters · also means 'Chinese'!",hintDe:"Beginnt mit 'Ch' · 3 Buchstaben · auch 'chinesisch'!",trick:"Zucker aus China.",example:{hi:"चीनी डालो।",en:"Add sugar.",de:"Zucker dazu.",tl:"Cheeni daalo."}},
{id:33,front:"Food",frontDe:"Essen",back:"खाना",tl:"Khaana",pron:"KHAA-naa",cat:"Food & Home",hint:"Starts with 'Kh' (guttural) · 3 letters · sounds like chewing",hintDe:"Beginnt mit 'Kh' · 3 Buchstaben · klingt wie Kauen",trick:"Im Kahn isst man.",example:{hi:"खाना तैयार है।",en:"Food is ready.",de:"Essen ist fertig.",tl:"Khaana taiyaar hai."}},
{id:34,front:"Fruits",frontDe:"Obst",back:"फल",tl:"Phal",pron:"full",cat:"Food & Home",hint:"Starts with 'Ph' · just 2 letters · like 'fall'",hintDe:"Beginnt mit 'Ph' · nur 2 Buchstaben · wie 'Fall'",trick:"Obst fällt.",example:{hi:"फल ताज़ा है।",en:"Fruits are fresh.",de:"Obst ist frisch.",tl:"Phal taaza hai."}},
{id:35,front:"Knife",frontDe:"Messer",back:"छुरी / चाकू",tl:"Chhuri / Chaaku",pron:"CHHOO-ree / CHAA-koo",cat:"Food & Home",hint:"Two words · both start 'Ch' · small vs big blade",hintDe:"Zwei Wörter · beide mit 'Ch'",trick:"Kurier bringt Messer.",example:{hi:"चाकू पास में है।",en:"Knife is nearby.",de:"Messer ist nah.",tl:"Chaaku paas mein hai."}},
{id:36,front:"Curtain",frontDe:"Vorhang",back:"पर्दा",tl:"Parda",pron:"PAR-daa",cat:"Food & Home",hint:"Starts with 'P' · 3 letters · like 'pardon'",hintDe:"Beginnt mit 'P' · 3 Buchstaben · Pardon",trick:"Pardon — Vorhang auf.",example:{hi:"पर्दा बंद करो।",en:"Close curtain.",de:"Vorhang zu.",tl:"Parda band karo."}},
{id:37,front:"Wall",frontDe:"Wand",back:"दीवार",tl:"Deevaar",pron:"dee-VAAR",cat:"Food & Home",hint:"Starts with 'D' · 4 letters · contains 'vaar'",hintDe:"Beginnt mit 'D' · 4 Buchstaben · Wahrheit an der Wand",trick:"Wahrheit an der Wand.",example:{hi:"दीवार सफ़ेद है।",en:"Wall is white.",de:"Die Wand ist weiß.",tl:"Deevaar safed hai."}},
{id:38,front:"Car",frontDe:"Auto",back:"गाड़ी",tl:"Gaadi",pron:"GAA-dee",cat:"Food & Home",hint:"Starts with 'G' · 3 letters · 'go-dee'",hintDe:"Beginnt mit 'G' · 3 Buchstaben · geh die Straße",trick:"Geh die Straße.",example:{hi:"गाड़ी बाहर है।",en:"Car is outside.",de:"Auto ist draußen.",tl:"Gaadi baahar hai."}},
{id:99,front:"Apple",frontDe:"Apfel",back:"सेब",tl:"Seb",pron:"sayb",cat:"Food & Home",hint:"Starts with 'S' · just 2 letters! · like 'sieve'",hintDe:"Beginnt mit 'S' · 2 Buchstaben · wie 'Sieb'",trick:"Sieb.",example:{hi:"सेब खाओ।",en:"Eat apple.",de:"Iss Apfel.",tl:"Seb khao."}},
{id:100,front:"Vegetable",frontDe:"Gemüse",back:"सब्ज़ी",tl:"Sabzi",pron:"SUB-zee",cat:"Food & Home",hint:"Starts with 'S' · 3 letters · like 'sub-zee'",hintDe:"Beginnt mit 'S' · 3 Buchstaben",trick:"Gemüse-Sub.",example:{hi:"सब्ज़ी लाओ।",en:"Bring veggies.",de:"Bring Gemüse.",tl:"Sabzi lao."}},
{id:101,front:"Banana",frontDe:"Banane",back:"केला",tl:"Kelaa",pron:"KAY-laa",cat:"Food & Home",hint:"Starts with 'K' · 3 letters · like 'cellar'",hintDe:"Beginnt mit 'K' · 3 Buchstaben · Keller",trick:"Keller.",example:{hi:"केला पीला है।",en:"Banana is yellow.",de:"Banane ist gelb.",tl:"Kelaa peela hai."}},
{id:112,front:"Egg",frontDe:"Ei",back:"अंडा",tl:"Andaa",pron:"UN-daa",cat:"Food & Home",hint:"Starts with 'A' · 3 letters · like 'under'",hintDe:"Beginnt mit 'A' · 3 Buchstaben · anders",trick:"Anders.",example:{hi:"अंडा पकाओ।",en:"Cook egg.",de:"Koch das Ei.",tl:"Andaa pakao."}},
{id:113,front:"Mirror",frontDe:"Spiegel",back:"शीशा",tl:"Sheeshaa",pron:"SHEE-shaa",cat:"Food & Home",hint:"Starts with 'Sh' · 3 letters · like a hookah pipe",hintDe:"Beginnt mit 'Sh' · 3 Buchstaben · Shisha",trick:"Shisha = Glas.",example:{hi:"शीशा साफ़ करो।",en:"Clean mirror.",de:"Putz den Spiegel.",tl:"Sheeshaa saaf karo."}},
{id:115,front:"Breakfast",frontDe:"Frühstück",back:"नाश्ता",tl:"Naashta",pron:"NAASH-taa",cat:"Food & Home",hint:"Starts with 'N' · 3 letters · 'naash' like 'naschen'",hintDe:"Beginnt mit 'N' · 3 Buchstaben · naschen!",trick:"Morgens naschen.",example:{hi:"नाश्ता तैयार है।",en:"Breakfast ready.",de:"Frühstück fertig.",tl:"Naashta taiyaar hai."}},
{id:124,front:"Bell",frontDe:"Glocke",back:"घंटी",tl:"Ghanti",pron:"GHUN-tee",cat:"Food & Home",hint:"Starts with 'Gh' (guttural) · 3 letters",hintDe:"Beginnt mit 'Gh' · 3 Buchstaben",trick:"Gong + Glocke.",example:{hi:"घंटी बज रही है।",en:"Bell is ringing.",de:"Die Glocke läutet.",tl:"Ghanti baj rahi hai."}},
{id:125,front:"Electricity",frontDe:"Strom",back:"बिजली",tl:"Bijli",pron:"BIJ-lee",cat:"Food & Home",hint:"Starts with 'B' · 3 letters · 'bij' like a zap!",hintDe:"Beginnt mit 'B' · 3 Buchstaben · Funke!",trick:"Bis Licht kommt.",example:{hi:"बिजली नहीं है।",en:"No electricity.",de:"Kein Strom.",tl:"Bijli nahin hai."}},
{id:132,front:"Clock",frontDe:"Uhr",back:"घड़ी",tl:"Ghadi",pron:"gha-DEE",cat:"Food & Home",hint:"Starts with 'Gh' (guttural) · 3 letters · also = watch",hintDe:"Beginnt mit 'Gh' · 3 Buchstaben · auch 'Armbanduhr'",trick:"Die Uhr tickt!",example:{hi:"घड़ी में आठ बजे हैं।",en:"It's eight o'clock.",de:"Es ist acht Uhr.",tl:"Ghadi mein aath baje hain."}},
{id:134,front:"Hat",frontDe:"Hut",back:"टोपी",tl:"Topi",pron:"TOH-pee",cat:"Food & Home",hint:"Starts with 'T' · 3 letters · 'top-i' — sits on top!",hintDe:"Beginnt mit 'T' · 3 Buchstaben · oben drauf!",trick:"Top-i — oben drauf!",example:{hi:"टोपी पहनो।",en:"Wear a hat.",de:"Setz den Hut auf.",tl:"Topi pehno."}},
{id:39,front:"City",frontDe:"Stadt",back:"शहर",tl:"Sheher",pron:"sheh-HER",cat:"Places",hint:"Starts with 'Sh' · 3 letters · 'she's here'",hintDe:"Beginnt mit 'Sh' · 3 Buchstaben",trick:"She's here.",example:{hi:"शहर बड़ा है।",en:"City is big.",de:"Stadt ist groß.",tl:"Sheher bada hai."}},
{id:40,front:"Village",frontDe:"Dorf",back:"गाँव",tl:"Gaanv",pron:"gaanv",cat:"Places",hint:"Starts with 'G' · 3 letters · nasal · like 'ganz'",hintDe:"Beginnt mit 'G' · 3 Buchstaben · wie 'ganz'",trick:"Ganzes Dorf.",example:{hi:"गाँव पास है।",en:"Village is near.",de:"Dorf ist nah.",tl:"Gaanv paas hai."}},
{id:41,front:"Inside",frontDe:"Drinnen",back:"अंदर",tl:"Andar",pron:"UN-dar",cat:"Places",hint:"Starts with 'A' · 3 letters · like 'under'",hintDe:"Beginnt mit 'A' · 3 Buchstaben · anders",trick:"Drinnen ist anders.",example:{hi:"अंदर आओ।",en:"Come inside.",de:"Komm rein.",tl:"Andar aao."}},
{id:42,front:"Outside",frontDe:"Draußen",back:"बाहर",tl:"Baahar",pron:"BAA-har",cat:"Places",hint:"Starts with 'B' · 3 letters · 'baa' like a sheep",hintDe:"Beginnt mit 'B' · 3 Buchstaben · Schaf draußen",trick:"Schaf draußen.",example:{hi:"बाहर जाओ।",en:"Go outside.",de:"Geh raus.",tl:"Baahar jao."}},
{id:43,front:"Near",frontDe:"Nah",back:"पास",tl:"Paas",pron:"paas",cat:"Places",hint:"Starts with 'P' · 2 letters · like English 'pass'",hintDe:"Beginnt mit 'P' · 2 Buchstaben · wie 'Pass'",trick:"Gebirgspass.",example:{hi:"पास है।",en:"It's near.",de:"Ist nah.",tl:"Paas hai."}},
{id:138,front:"Floor",frontDe:"Boden",back:"फ़र्श / ज़मीन",tl:"Farsh / Zameen",pron:"farsh / za-MEEN",cat:"Places",hint:"Two options · first 'F' (2 letters) · second 'Z' (3 letters)",hintDe:"Zwei Wörter · erstes mit 'F' · zweites mit 'Z'",trick:"Farsh — die Erde unter dir!",example:{hi:"ज़मीन गीली है।",en:"Floor is wet.",de:"Boden ist nass.",tl:"Zameen geeli hai."}},
{id:44,front:"Month",frontDe:"Monat",back:"महीना",tl:"Maheena",pron:"ma-HEE-naa",cat:"Time",hint:"Starts with 'M' · 4 letters · monthly machine",hintDe:"Beginnt mit 'M' · 4 Buchstaben · Maschine",trick:"Monats-Maschine.",example:{hi:"एक महीना बाद।",en:"After one month.",de:"Nach einem Monat.",tl:"Ek maheena baad."}},
{id:45,front:"December",frontDe:"Dezember",back:"दिसंबर",tl:"Disambar",pron:"di-SUM-bar",cat:"Time",hint:"Almost identical pronunciation · starts with 'D'",hintDe:"Fast identisch! · Beginnt mit 'D'",trick:"Dezember.",example:{hi:"दिसंबर में सर्दी।",en:"December is cold.",de:"Dezember ist kalt.",tl:"Disambar mein sardi."}},
{id:46,front:"Date",frontDe:"Datum",back:"तारीख़",tl:"Taareekh",pron:"taa-REEKH",cat:"Time",hint:"Starts with 'T' · 3 letters · guttural 'kh' at end",hintDe:"Beginnt mit 'T' · 3 Buchstaben · frag Tarik!",trick:"Frag Tarik.",example:{hi:"आज की तारीख़?",en:"Today's date?",de:"Welches Datum?",tl:"Aaj ki taareekh?"}},
{id:47,front:"Day",frontDe:"Tag",back:"दिन",tl:"Din",pron:"din",cat:"Time",hint:"Starts with 'D' · 2 letters! · like 'din' (noise)",hintDe:"Beginnt mit 'D' · 2 Buchstaben · Ding ohne g",trick:"Ding.",example:{hi:"अच्छा दिन।",en:"Good day.",de:"Guter Tag.",tl:"Accha din."}},
{id:48,front:"Birthday",frontDe:"Geburtstag",back:"जन्मदिन",tl:"Janamdin",pron:"ja-NAM-din",cat:"Time",hint:"Two words: 'janam' (birth) + 'din' (day) · starts 'J'",hintDe:"Janam + din — wie 'Geburts-tag'!",trick:"Geburts-tag.",example:{hi:"जन्मदिन मुबारक!",en:"Happy birthday!",de:"Alles Gute!",tl:"Janamdin mubarak!"}},
{id:49,front:"Often",frontDe:"Oft",back:"अक्सर",tl:"Aksar",pron:"UK-sar",cat:"Time",hint:"Starts with 'A' · 3 letters · first syllable like 'UK'",hintDe:"Beginnt mit 'A' · 3 Buchstaben · UK-Akzent",trick:"UK-Akzent.",example:{hi:"अक्सर आता हूँ।",en:"I come often.",de:"Ich komme oft.",tl:"Aksar aata hoon."}},
{id:50,front:"Always",frontDe:"Immer",back:"हमेशा",tl:"Hamesha",pron:"ha-MAY-sha",cat:"Time",hint:"Starts with 'H' · 4 letters · Ha-May-Sha!",hintDe:"Beginnt mit 'H' · 4 Buchstaben · Ha, Me, Schatz!",trick:"Ha, Me, Schatz!",example:{hi:"हमेशा साथ।",en:"Always together.",de:"Immer zusammen.",tl:"Hamesha saath."}},
{id:102,front:"Later",frontDe:"Später",back:"बाद में",tl:"Baad mein",pron:"baad mayn",cat:"Time",hint:"Two words · first 'B' · like 'bath' — later!",hintDe:"Zwei Wörter · erstes mit 'B' · Bad",trick:"Später ins Bad.",example:{hi:"बाद में।",en:"Later.",de:"Später.",tl:"Baad mein."}},
{id:103,front:"Immediately",frontDe:"Sofort",back:"तुरंत",tl:"Turant",pron:"too-RUNT",cat:"Time",hint:"Starts with 'T' · 3 letters · like 'to-rant'",hintDe:"Beginnt mit 'T' · 3 Buchstaben · Turnen gerannt!",trick:"Turnen gerannt.",example:{hi:"तुरंत आओ!",en:"Come now!",de:"Komm sofort!",tl:"Turant aao!"}},
{id:133,front:"Evening",frontDe:"Abend",back:"शाम",tl:"Shaam",pron:"shaam",cat:"Time",hint:"Starts with 'Sh' · just 2 letters · long 'aa'",hintDe:"Beginnt mit 'Sh' · 2 Buchstaben · langes 'aa'",trick:"Shaam = Abend.",example:{hi:"शाम को मिलते हैं।",en:"Meet in the evening.",de:"Treffen uns abends.",tl:"Shaam ko milte hain."}},
{id:51,front:"Happiness",frontDe:"Glück",back:"ख़ुशी",tl:"Khushi",pron:"KHOO-shee",cat:"Emotions",hint:"Starts with 'Kh' (guttural) · 3 letters · like 'cushy'",hintDe:"Beginnt mit 'Kh' · 3 Buchstaben · kuscheln",trick:"Kuscheln = glücklich.",example:{hi:"ख़ुशी बड़ी चीज़।",en:"Happiness matters.",de:"Glück ist wichtig.",tl:"Khushi badi cheez."}},
{id:52,front:"Anger",frontDe:"Wut",back:"गुस्सा",tl:"Gussa",pron:"GOOS-saa",cat:"Emotions",hint:"Starts with 'G' · 3 letters · like a 'gust'",hintDe:"Beginnt mit 'G' · 3 Buchstaben · Guss der Wut",trick:"Regenguss der Wut.",example:{hi:"गुस्सा मत करो।",en:"Don't be angry.",de:"Sei nicht wütend.",tl:"Gussa mat karo."}},
{id:53,front:"Dream",frontDe:"Traum",back:"सपना",tl:"Sapna",pron:"SUP-naa",cat:"Emotions",hint:"Starts with 'S' · 3 letters · like 'sauna'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · Sauna",trick:"Sauna-Traum.",example:{hi:"सपना बड़ा है।",en:"Big dream.",de:"Großer Traum.",tl:"Sapna bada hai."}},
{id:54,front:"Fun",frontDe:"Spaß",back:"मज़ा",tl:"Mazaa",pron:"ma-ZAA",cat:"Emotions",hint:"Starts with 'M' · 3 letters · like 'matza'",hintDe:"Beginnt mit 'M' · 3 Buchstaben · Matza",trick:"Matza backen.",example:{hi:"मज़ा आया!",en:"Had fun!",de:"Hat Spaß gemacht!",tl:"Mazaa aaya!"}},
{id:55,front:"Health",frontDe:"Gesundheit",back:"सेहत",tl:"Sehat",pron:"SEH-hat",cat:"Emotions",hint:"Starts with 'S' · 3 letters · 'seh' + 'hat'",hintDe:"Beginnt mit 'S' · seh + hat = gesund",trick:"Seh + hat = gesund.",example:{hi:"सेहत का ध्यान रखो।",en:"Take care of health.",de:"Pass auf Gesundheit auf.",tl:"Sehat ka dhyaan rakho."}},
{id:126,front:"Worries",frontDe:"Sorgen",back:"चिंता",tl:"Chintaa",pron:"CHIN-taa",cat:"Emotions",hint:"Starts with 'Ch' · 3 letters · chin-deep in trouble!",hintDe:"Beginnt mit 'Ch' · bis zum Kinn in Sorgen!",trick:"Bis zum Kinn.",example:{hi:"चिंता मत करो।",en:"Don't worry.",de:"Keine Sorgen.",tl:"Chintaa mat karo."}},
{id:56,front:"Different",frontDe:"Anders",back:"अलग",tl:"Alag",pron:"a-LUG",cat:"Adjectives",hint:"Starts with 'A' · 3 letters · like 'a-lag'",hintDe:"Beginnt mit 'A' · 3 Buchstaben · Alltag",trick:"Jeder Alltag anders.",example:{hi:"यह अलग है।",en:"This is different.",de:"Das ist anders.",tl:"Yeh alag hai."}},
{id:57,front:"Polite",frontDe:"Höflich",back:"विनम्र",tl:"Vinamra",pron:"vi-NUM-ra",cat:"Adjectives",hint:"Starts with 'V' · 4 letters · 'vi' + 'namra' (bowing)",hintDe:"Beginnt mit 'V' · sich verbeugen",trick:"Sich verbeugen.",example:{hi:"विनम्र रहो।",en:"Be polite.",de:"Sei höflich.",tl:"Vinamra raho."}},
{id:58,front:"Honest",frontDe:"Ehrlich",back:"ईमानदार",tl:"Imaandaar",pron:"ee-MAAN-daar",cat:"Adjectives",hint:"Starts with 'I' · 'imaan' (faith) + 'daar' (keeper)",hintDe:"'Imaan' (Glaube) + 'daar' (Hüter)",trick:"Glaubens-Hüter.",example:{hi:"ईमानदार रहो।",en:"Be honest.",de:"Sei ehrlich.",tl:"Imaandaar raho."}},
{id:59,front:"Fast",frontDe:"Schnell",back:"तेज़ / जल्दी",tl:"Tez / Jaldi",pron:"tayz / JUL-dee",cat:"Adjectives",hint:"Two options · 'T' (2 letters, rhymes with 'days') · 'J' (3 letters = hurry!)",hintDe:"Zwei Wörter · 'T' · 'J' — Beeil dich!",trick:"Tess rennt + Jaldi!",example:{hi:"जल्दी करो!",en:"Hurry up!",de:"Beeil dich!",tl:"Jaldi karo!"}},
{id:60,front:"Cheap",frontDe:"Billig",back:"सस्ता",tl:"Sasta",pron:"SUS-taa",cat:"Adjectives",hint:"Starts with 'S' · 3 letters · rhymes with 'pasta'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · Pasta",trick:"Billige Pasta.",example:{hi:"बहुत सस्ता।",en:"Very cheap.",de:"Sehr billig.",tl:"Bahut sasta."}},
{id:61,front:"Clean",frontDe:"Sauber",back:"साफ़",tl:"Saaf",pron:"saaf",cat:"Adjectives",hint:"Starts with 'S' · just 2 letters! · like 'Saft'",hintDe:"Beginnt mit 'S' · 2 Buchstaben · Saft",trick:"Sauberer Saft.",example:{hi:"साफ़ है।",en:"It's clean.",de:"Ist sauber.",tl:"Saaf hai."}},
{id:62,front:"Dry",frontDe:"Trocken",back:"सूखा",tl:"Sookha",pron:"SOO-khaa",cat:"Adjectives",hint:"Starts with 'S' · 3 letters · 'soo' + guttural 'kha'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · Suche",trick:"Trockenes Land suchen.",example:{hi:"सूखा है।",en:"It's dry.",de:"Ist trocken.",tl:"Sookha hai."}},
{id:63,front:"Wet",frontDe:"Nass",back:"गीला",tl:"Geela",pron:"GEE-laa",cat:"Adjectives",hint:"Starts with 'G' · 3 letters · like 'gelato' melting!",hintDe:"Beginnt mit 'G' · 3 Buchstaben · Gelato",trick:"Gelato schmilzt.",example:{hi:"सब गीला है।",en:"Everything wet.",de:"Alles nass.",tl:"Sab geela hai."}},
{id:64,front:"Easy",frontDe:"Einfach",back:"आसान",tl:"Aasaan",pron:"aa-SAAN",cat:"Adjectives",hint:"Starts with 'Aa' · 3 letters · sigh of relief!",hintDe:"Beginnt mit 'Aa' · 3 Buchstaben · angenehm!",trick:"Angenehm.",example:{hi:"आसान है।",en:"It's easy.",de:"Ist einfach.",tl:"Aasaan hai."}},
{id:65,front:"Difficult",frontDe:"Schwierig",back:"मुश्किल",tl:"Mushkil",pron:"MUSH-kil",cat:"Adjectives",hint:"Starts with 'M' · 4 letters · like prying a 'mussel'",hintDe:"Beginnt mit 'M' · 4 Buchstaben · Muschel",trick:"Muschel öffnen.",example:{hi:"मुश्किल है।",en:"It's difficult.",de:"Ist schwierig.",tl:"Mushkil hai."}},
{id:66,front:"Bad",frontDe:"Schlecht",back:"बुरा",tl:"Buraa",pron:"boo-RAA",cat:"Adjectives",hint:"Starts with 'B' · 3 letters · 'Boo!'",hintDe:"Beginnt mit 'B' · 3 Buchstaben · Buhrufe",trick:"Buhrufe.",example:{hi:"बुरा मत मानो।",en:"Don't feel bad.",de:"Nimm's nicht übel.",tl:"Buraa mat maano."}},
{id:67,front:"Interesting",frontDe:"Interessant",back:"दिलचस्प",tl:"Dilchasp",pron:"dil-CHUSP",cat:"Adjectives",hint:"Starts with 'D' · 'dil' = heart · grips your heart",hintDe:"'Dil' = Herz · klebt am Herzen",trick:"Am Herzen kleben.",example:{hi:"दिलचस्प!",en:"Interesting!",de:"Interessant!",tl:"Dilchasp!"}},
{id:68,front:"Enough",frontDe:"Genug",back:"काफ़ी / बस",tl:"Kaafi / Bas",pron:"KAA-fee / bus",cat:"Adjectives",hint:"Two options · 'K' (like coffee!) · 'B' (bus stops!)",hintDe:"Kaffee + Bus = Stopp!",trick:"Kaffee + Bus.",example:{hi:"बस! काफ़ी!",en:"Stop! Enough!",de:"Stopp! Genug!",tl:"Bas! Kaafi!"}},
{id:104,front:"Young",frontDe:"Jung",back:"जवान",tl:"Javaan",pron:"ja-VAAN",cat:"Adjectives",hint:"Starts with 'J' · 3 letters · programming language",hintDe:"Beginnt mit 'J' · 3 Buchstaben · Java",trick:"Java = jung.",example:{hi:"वह जवान है।",en:"He's young.",de:"Er ist jung.",tl:"Woh javaan hai."}},
{id:111,front:"Cold",frontDe:"Kalt",back:"सर्दी",tl:"Sardi",pron:"SAR-dee",cat:"Adjectives",hint:"Starts with 'S' · 3 letters · cold-water fish",hintDe:"Beginnt mit 'S' · 3 Buchstaben · Sardine",trick:"Sardine.",example:{hi:"सर्दी है।",en:"It's cold.",de:"Ist kalt.",tl:"Sardi hai."}},
{id:127,front:"Wrong",frontDe:"Falsch",back:"ग़लत",tl:"Galat",pron:"ga-LUT",cat:"Adjectives",hint:"Starts with 'G' · 3 letters · 'galoot' = clumsy",hintDe:"Beginnt mit 'G' · 3 Buchstaben · Galopp",trick:"Im Galopp = Fehler.",example:{hi:"ग़लत है।",en:"It's wrong.",de:"Ist falsch.",tl:"Galat hai."}},
{id:128,front:"Empty",frontDe:"Leer",back:"ख़ाली",tl:"Khaali",pron:"KHAA-lee",cat:"Adjectives",hint:"Starts with 'Kh' (guttural) · 3 letters · hollow sound",hintDe:"Beginnt mit 'Kh' · 3 Buchstaben · kahl",trick:"Kahl = leer.",example:{hi:"ख़ाली है।",en:"It's empty.",de:"Ist leer.",tl:"Khaali hai."}},
{id:136,front:"Fat",frontDe:"Dick",back:"मोटा",tl:"Motaa",pron:"MOH-taa",cat:"Adjectives",hint:"Starts with 'M' · 3 letters · like 'motor'",hintDe:"Beginnt mit 'M' · 3 Buchstaben · Motor",trick:"Motor — schwer und groß!",example:{hi:"यह आदमी मोटा है।",en:"This man is fat.",de:"Dieser Mann ist dick.",tl:"Yeh aadmi motaa hai."}},
{id:69,front:"To speak",frontDe:"Sprechen",back:"बोलना",tl:"Bolnaa",pron:"BOWL-naa",cat:"Verbs",hint:"Starts with 'B' · 4 letters · bowling alley!",hintDe:"Beginnt mit 'B' · 4 Buchstaben · Bowling!",trick:"Bowling.",example:{hi:"हिंदी बोलो।",en:"Speak Hindi.",de:"Sprich Hindi.",tl:"Hindi bolo."}},
{id:70,front:"To learn",frontDe:"Lernen",back:"सीखना",tl:"Seekhna",pron:"SEEKH-naa",cat:"Verbs",hint:"Starts with 'S' · 4 letters · like 'seek' knowledge!",hintDe:"Beginnt mit 'S' · 4 Buchstaben · seek!",trick:"Wissen suchen.",example:{hi:"हिंदी सीखो।",en:"Learn Hindi.",de:"Lerne Hindi.",tl:"Hindi seekho."}},
{id:71,front:"To walk",frontDe:"Gehen",back:"चलना",tl:"Chalnaa",pron:"CHUL-naa",cat:"Verbs",hint:"Starts with 'Ch' · 4 letters · 'Chal!' = Let's go!",hintDe:"Beginnt mit 'Ch' · 4 Buchstaben · Schall",trick:"Schall beim Gehen.",example:{hi:"चलो बाहर।",en:"Let's go out.",de:"Gehen wir raus.",tl:"Chalo baahar."}},
{id:72,front:"To read",frontDe:"Lesen",back:"पढ़ना",tl:"Padhna",pron:"PUDH-naa",cat:"Verbs",hint:"Starts with 'P' · 3 letters · like 'pad' + 'na'",hintDe:"Beginnt mit 'P' · 3 Buchstaben · Pad",trick:"Pad = lesen.",example:{hi:"किताब पढ़ो।",en:"Read a book.",de:"Lies ein Buch.",tl:"Kitaab padho."}},
{id:73,front:"To ask",frontDe:"Fragen",back:"पूछना",tl:"Poochhnaa",pron:"POOCHH-naa",cat:"Verbs",hint:"Starts with 'P' · 4 letters · 'pooch' = dog begging!",hintDe:"Beginnt mit 'P' · 4 Buchstaben · Hund bettelt",trick:"Hund fragt.",example:{hi:"पूछो?",en:"Ask?",de:"Frag?",tl:"Poochho?"}},
{id:74,front:"To start",frontDe:"Anfangen",back:"शुरू करना",tl:"Shuru karnaa",pron:"shoo-ROO kar-NAA",cat:"Verbs",hint:"Two words · first 'Sh' · 'shoo!' into action!",hintDe:"Zwei Wörter · 'Sh' · Schuhe an!",trick:"Schuhe an.",example:{hi:"शुरू करो!",en:"Start!",de:"Fang an!",tl:"Shuru karo!"}},
{id:105,front:"To understand",frontDe:"Verstehen",back:"समझना",tl:"Samajhna",pron:"sa-MUJH-naa",cat:"Verbs",hint:"Starts with 'S' · 4 letters · Sam says 'Ah-ha!'",hintDe:"Beginnt mit 'S' · 4 Buchstaben · Sam versteht!",trick:"Sam versteht.",example:{hi:"समझ आया?",en:"Understood?",de:"Verstanden?",tl:"Samajh aaya?"}},
{id:114,front:"To sit",frontDe:"Sitzen",back:"बैठना",tl:"Baithna",pron:"BAITH-naa",cat:"Verbs",hint:"Starts with 'B' · 4 letters · 'baith' = 'byte'",hintDe:"Beginnt mit 'B' · 4 Buchstaben · Byte",trick:"Byte = sitzen.",example:{hi:"बैठो।",en:"Sit.",de:"Setz dich.",tl:"Baitho."}},
{id:140,front:"To laugh",frontDe:"Lachen",back:"हँसना",tl:"Hansna",pron:"HUS-naa",cat:"Verbs",hint:"Starts with 'H' · 4 letters · sounds like 'Hans-na'",hintDe:"Beginnt mit 'H' · 4 Buchstaben · Hans lacht!",trick:"Hans lacht immer!",example:{hi:"हँसो!",en:"Laugh!",de:"Lach!",tl:"Hanso!"}},
{id:75,front:"Message",frontDe:"Nachricht",back:"संदेश",tl:"Sandesh",pron:"sun-DAYSH",cat:"Common Words",hint:"Starts with 'S' · 3 letters · written in 'sand'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · Sand",trick:"Sand-Nachricht.",example:{hi:"संदेश भेजो।",en:"Send message.",de:"Schick Nachricht.",tl:"Sandesh bhejo."}},
{id:76,front:"Answer",frontDe:"Antwort",back:"जवाब",tl:"Javaab",pron:"ja-VAAB",cat:"Common Words",hint:"Starts with 'J' · 3 letters · like 'ja!' (yes)",hintDe:"Beginnt mit 'J' · 3 Buchstaben · 'Ja!'",trick:"Ja = Antwort.",example:{hi:"जवाब दो।",en:"Give answer.",de:"Gib Antwort.",tl:"Javaab do."}},
{id:77,front:"Maybe",frontDe:"Vielleicht",back:"शायद",tl:"Shaayad",pron:"SHAA-yad",cat:"Common Words",hint:"Starts with 'Sh' · 3 letters · like 'Schade'",hintDe:"Beginnt mit 'Sh' · 3 Buchstaben · Schade",trick:"Schade.",example:{hi:"शायद कल।",en:"Maybe tomorrow.",de:"Vielleicht morgen.",tl:"Shaayad kal."}},
{id:80,front:"Or",frontDe:"Oder",back:"या",tl:"Ya",pron:"yaa",cat:"Common Words",hint:"Just 1 letter! · like 'yeah?'",hintDe:"Nur 1 Buchstabe! · wie 'ja?'",trick:"Ja.",example:{hi:"चाय या कॉफ़ी?",en:"Tea or coffee?",de:"Tee oder Kaffee?",tl:"Chai ya coffee?"}},
{id:81,front:"Both",frontDe:"Beide",back:"दोनों",tl:"Donon",pron:"DOH-non",cat:"Common Words",hint:"Starts with 'D' · 3 letters · starts like 'do' (two!)",hintDe:"Beginnt mit 'D' · 3 Buchstaben · Donner",trick:"Donner — doppelt.",example:{hi:"दोनों अच्छे।",en:"Both good.",de:"Beide gut.",tl:"Donon acche."}},
{id:82,front:"With",frontDe:"Mit",back:"के साथ",tl:"Ke saath",pron:"kay SAATH",cat:"Common Words",hint:"Two words · second 'S' · like 'Saat' (seed)",hintDe:"Zwei Wörter · 'S' · Saat pflanzen",trick:"Zusammen pflanzen.",example:{hi:"मेरे साथ चलो।",en:"Come with me.",de:"Komm mit mir.",tl:"Mere saath chalo."}},
{id:83,front:"For",frontDe:"Für",back:"के लिए",tl:"Ke liye",pron:"kay LEE-yay",cat:"Common Words",hint:"Two words · second starts 'L' · 'ke lee-yay'",hintDe:"Zwei Wörter · zweites mit 'L'",trick:"Für Kelly.",example:{hi:"मेरे लिए।",en:"For me.",de:"Für mich.",tl:"Mere liye."}},
{id:84,front:"Too / Also",frontDe:"Auch",back:"भी",tl:"Bhi",pron:"bhee",cat:"Common Words",hint:"Just 1 letter! · breathy 'Bh' · buzzing bee",hintDe:"Nur 1 Buchstabe! · Biene",trick:"Biene will auch.",example:{hi:"मैं भी।",en:"Me too.",de:"Ich auch.",tl:"Main bhi."}},
{id:85,front:"Right",frontDe:"Richtig",back:"सही",tl:"Sahi",pron:"sa-HEE",cat:"Common Words",hint:"Starts with 'S' · 2 letters · 'Sahne' = right choice",hintDe:"Beginnt mit 'S' · 2 Buchstaben · Sahne",trick:"Sahne — richtig.",example:{hi:"सही!",en:"Right!",de:"Richtig!",tl:"Sahi!"}},
{id:79,front:"That's why",frontDe:"Deshalb",back:"इसलिए",tl:"Isliye",pron:"ISS-lee-yay",cat:"Common Words",hint:"Starts with 'I' · 4 letters · 'iss-lee-yay'",hintDe:"Beginnt mit 'I' · 4 Buchstaben · iss lieber",trick:"Iss lieber.",example:{hi:"इसलिए अंदर रहो।",en:"So stay in.",de:"Deshalb bleib drin.",tl:"Isliye andar raho."}},
{id:106,front:"More",frontDe:"Mehr",back:"और / ज़्यादा",tl:"Aur / Zyaada",pron:"OWR / zyaa-DAA",cat:"Common Words",hint:"Two options · 'A' (2 letters, like 'Ohr') · 'Z'",hintDe:"Zwei Wörter · 'A' (Ohr) · 'Z'",trick:"Mehr Ohren.",example:{hi:"और?",en:"More?",de:"Mehr?",tl:"Aur?"}},
{id:107,front:"Group",frontDe:"Gruppe",back:"समूह",tl:"Samooh",pron:"sa-MOOH",cat:"Common Words",hint:"Starts with 'S' · 3 letters · 'sa-mooh'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · Sam ruft",trick:"Sam ruft.",example:{hi:"बड़ा समूह।",en:"Big group.",de:"Große Gruppe.",tl:"Bada samooh."}},
{id:110,front:"Journey",frontDe:"Reise",back:"यात्रा",tl:"Yaatraa",pron:"YAA-traa",cat:"Common Words",hint:"Starts with 'Y' · 4 letters · carry (trage) bags!",hintDe:"Beginnt mit 'Y' · 4 Buchstaben · Ja, Trage!",trick:"Ja, Trage!",example:{hi:"यात्रा लंबी है।",en:"Long journey.",de:"Lange Reise.",tl:"Yaatraa lambi hai."}},
{id:129,front:"Truth",frontDe:"Wahrheit",back:"सच",tl:"Sach",pron:"such",cat:"Common Words",hint:"Starts with 'S' · 2 letters! · like English 'such'",hintDe:"Beginnt mit 'S' · 2 Buchstaben · Sache",trick:"Klare Sache.",example:{hi:"सच बोलो।",en:"Speak truth.",de:"Sag die Wahrheit.",tl:"Sach bolo."}},
{id:130,front:"Goodbye",frontDe:"Tschüss",back:"अलविदा",tl:"Alvida",pron:"al-vi-DAA",cat:"Common Words",hint:"Starts with 'A' · 4 letters · 'al-vi-daa'",hintDe:"Beginnt mit 'A' · 4 Buchstaben · Alle Vidas sagen Tschüss",trick:"Alle Vidas sagen Tschüss!",example:{hi:"अलविदा दोस्त।",en:"Goodbye friend.",de:"Tschüss Freund.",tl:"Alvida dost."}},
{id:137,front:"Price",frontDe:"Preis",back:"कीमत / दाम",tl:"Keemat / Daam",pron:"KEE-mat / daam",cat:"Common Words",hint:"Two options · 'K' (3 letters) · 'D' (2 letters)",hintDe:"Zwei Wörter · 'K' · 'D' (nur 2 Buchstaben)",trick:"Keemat — wie viel kostet es?",example:{hi:"कीमत क्या है?",en:"What's the price?",de:"Was ist der Preis?",tl:"Keemat kya hai?"}},
{id:139,front:"Decision",frontDe:"Entscheidung",back:"फ़ैसला",tl:"Faislaa",pron:"FAIS-laa",cat:"Common Words",hint:"Starts with 'F' · 3 letters · 'fais-laa'",hintDe:"Beginnt mit 'F' · 3 Buchstaben",trick:"Fass den Entschluss!",example:{hi:"फ़ैसला करो।",en:"Make a decision.",de:"Triff eine Entscheidung.",tl:"Faislaa karo."}},
{id:141,front:"Question",frontDe:"Frage",back:"सवाल",tl:"Sawaal",pron:"sa-WAAL",cat:"Common Words",hint:"Starts with 'S' · 3 letters · ends '-aal'",hintDe:"Beginnt mit 'S' · 3 Buchstaben · endet '-aal'",trick:"So wahl-los — Fragen ohne Ende!",example:{hi:"एक सवाल।",en:"One question.",de:"Eine Frage.",tl:"Ek sawaal."}},
{id:78,front:"Something else?",frontDe:"Noch etwas?",back:"और कुछ?",tl:"Aur kuchh?",pron:"OWR kootch?",cat:"Sentences",hint:"'Aur' (more) + 'kuchh' (something) · shopkeeper's line!",hintDe:"'Aur' (mehr) + 'kuchh' (etwas)",trick:"Ohr + Kutsche.",example:{hi:"और कुछ?",en:"Anything else?",de:"Noch etwas?",tl:"Aur kuchh?"}},
{id:86,front:"I live in Hamburg",frontDe:"Ich wohne in Hamburg",back:"मैं हैम्बर्ग में रहता हूँ",tl:"Main Hamburg mein rehta hoon",pron:"main Hamburg mayn REH-taa hoon",cat:"Sentences",hint:"Main = I · mein = in · rehta hoon = live",hintDe:"Main = ich · mein = in · rehta hoon = wohne",trick:"Fast wie Deutsch.",example:{hi:"मैं हैम्बर्ग में रहता हूँ।",en:"I live in Hamburg.",de:"Ich wohne in Hamburg.",tl:"Main Hamburg mein rehta hoon."}},
{id:108,front:"I am doing well",frontDe:"Mir geht es gut",back:"मैं ठीक हूँ",tl:"Main theek hoon",pron:"main THEEK hoon",cat:"Sentences",hint:"3 words · 'theek' = 'tick' — everything ticks right!",hintDe:"'Theek' wie 'Tick' — alles tickt richtig!",trick:"Tick.",example:{hi:"मैं ठीक हूँ।",en:"I'm fine.",de:"Mir geht's gut.",tl:"Main theek hoon."}},
{id:116,front:"I'm good as well",frontDe:"Mir geht es auch gut",back:"मैं भी ठीक हूँ",tl:"Main bhi theek hoon",pron:"main bhee THEEK hoon",cat:"Sentences",hint:"Add 'bhi' (also) into 'main theek hoon'!",hintDe:"Füge 'bhi' (auch) ein!",trick:"Bhi = auch.",example:{hi:"मैं भी ठीक हूँ।",en:"I'm good too.",de:"Mir geht es auch gut.",tl:"Main bhi theek hoon."}},
{id:142,front:"Which day is today?",frontDe:"Welcher Tag ist heute?",back:"आज कौन सा दिन है?",tl:"Aaj kaun sa din hai?",pron:"aaj KOWN sa din hai?",cat:"Sentences",hint:"'Aaj' = today · 'kaun sa' = which · 'din' = day",hintDe:"'Aaj' = heute · 'kaun sa' = welcher · 'din' = Tag",trick:"Aaj + kaun sa + din + hai?",example:{hi:"आज कौन सा दिन है?",en:"Which day is today?",de:"Welcher Tag ist heute?",tl:"Aaj kaun sa din hai?"}},
{id:143,front:"Where is your chair?",frontDe:"Wo ist dein Stuhl?",back:"तुम्हारी कुर्सी कहाँ है?",tl:"Tumhari kursi kahan hai?",pron:"tum-HAA-ree KUR-see ka-HAAN hai?",cat:"Sentences",hint:"'Tumhari' = your · 'kursi' = chair · 'kahan' = where",hintDe:"'Tumhari' = dein · 'kursi' = Stuhl · 'kahan' = wo",trick:"Tumhari + kursi + kahan + hai?",example:{hi:"तुम्हारी कुर्सी कहाँ है?",en:"Where is your chair?",de:"Wo ist dein Stuhl?",tl:"Tumhari kursi kahan hai?"}},
{id:144,front:"How is the book?",frontDe:"Wie ist das Buch?",back:"किताब कैसी है?",tl:"Kitaab kaisi hai?",pron:"ki-TAAB KAY-see hai?",cat:"Sentences",hint:"'Kitaab' = book · 'kaisi' = how (fem.) · 'hai' = is",hintDe:"'Kitaab' = Buch · 'kaisi' = wie · 'hai' = ist",trick:"Kitaab + kaisi + hai?",example:{hi:"किताब कैसी है?",en:"How is the book?",de:"Wie ist das Buch?",tl:"Kitaab kaisi hai?"}},
{id:145,front:"How big is your house?",frontDe:"Wie groß ist dein Haus?",back:"तुम्हारा घर कितना बड़ा है?",tl:"Tumhara ghar kitna bada hai?",pron:"tum-HAA-ra ghar KIT-na ba-DAA hai?",cat:"Sentences",hint:"'Tumhara' = your · 'ghar' = house · 'kitna' = how much · 'bada' = big",hintDe:"'Tumhara' = dein · 'ghar' = Haus · 'kitna' = wie viel · 'bada' = groß",trick:"Tumhara + ghar + kitna + bada + hai?",example:{hi:"तुम्हारा घर कितना बड़ा है?",en:"How big is your house?",de:"Wie groß ist dein Haus?",tl:"Tumhara ghar kitna bada hai?"}},
];

const CATEGORIES=["All",...Array.from(new Set(ALL_CARDS.map(c=>c.cat)))];
const CC={Numbers:"#E07850","Family & People":"#A070C0","Body Parts":"#D86888","Nature & Weather":"#50A8B8",Colors:"#C8A040","Food & Home":"#58B070",Places:"#5890D0",Time:"#D89050",Emotions:"#C86088",Adjectives:"#50A080",Verbs:"#8870B8","Common Words":"#6878C0",Sentences:"#D08058"};
const LVL_C=["#D06060","#D89050","#C8A040","#80B050","#40A050"];
const LVL_D=[0,48*36e5,96*36e5,7*864e5,30*864e5];
function cleanForSpeech(t){return t.replace(/\s*\(.*?\)\s*/g," ").replace(/\s*\/\s*/g," ").replace(/\n/g," ").trim();}

const TL={bgGrad:"linear-gradient(155deg,#F8F6F3 0%,#F2EDE8 30%,#ECE8F2 55%,#E8F0F0 75%,#F5F2EA 100%)",cardFront:"linear-gradient(155deg,#FFF,#FDFBF8 40%,#F8F6FD 70%,#F5F8FB)",text:"#1E1A20",sub:"#58505E",muted:"#908898",faint:"#C8C0D0",hintBg:"rgba(160,112,192,.06)",hintBd:"rgba(160,112,192,.15)",hintTx:"#5E4878",trickBg:"rgba(88,176,112,.06)",trickBd:"rgba(88,176,112,.16)",trickTx:"#38784A",pillBg:"#FFF",pillBd:"rgba(0,0,0,.06)",btnBg:"#FFF",btnBd:"rgba(0,0,0,.08)",btnTx:"#78708A",dotBg:"rgba(0,0,0,.07)",divider:"rgba(0,0,0,.06)",cardShadow:"0 8px 32px rgba(30,20,40,.06),0 2px 8px rgba(0,0,0,.03)",accent:"#C06080",pronBg:"rgba(192,96,128,.06)",pronBd:"rgba(192,96,128,.16)",speedBg:"rgba(192,96,128,.04)",speedBd:"rgba(192,96,128,.10)",speedActive:"rgba(192,96,128,.12)",inputBg:"#FFF",inputBd:"rgba(0,0,0,.10)",overlayBg:"rgba(248,246,243,.98)",tabBg:"#FFF",tabBd:"rgba(0,0,0,.06)",barFill:"#C06080",exBg:"rgba(80,168,184,.05)",exBd:"rgba(80,168,184,.14)",exTx:"#28708A",catCardBg:"#FFF",catCardBd:"rgba(0,0,0,.05)",catCardShadow:"0 2px 12px rgba(0,0,0,.04)"};
const TD={bgGrad:"linear-gradient(155deg,#14101A 0%,#181420 30%,#121418 55%,#161218 75%,#181418 100%)",cardFront:"linear-gradient(155deg,#201828,#1A1620 40%,#161420)",text:"#EDE8F0",sub:"#8A8098",muted:"#585060",faint:"#383040",hintBg:"rgba(255,255,255,.04)",hintBd:"rgba(255,255,255,.08)",hintTx:"#8A8098",trickBg:"rgba(88,176,112,.08)",trickBd:"rgba(88,176,112,.14)",trickTx:"#78C098",pillBg:"rgba(255,255,255,.04)",pillBd:"rgba(255,255,255,.06)",btnBg:"rgba(255,255,255,.05)",btnBd:"rgba(255,255,255,.08)",btnTx:"#8A8098",dotBg:"rgba(255,255,255,.08)",divider:"rgba(255,255,255,.05)",cardShadow:"0 8px 32px rgba(0,0,0,.4),inset 0 1px 0 rgba(255,255,255,.03)",accent:"#E08898",pronBg:"rgba(224,136,152,.10)",pronBd:"rgba(224,136,152,.20)",speedBg:"rgba(255,255,255,.03)",speedBd:"rgba(255,255,255,.06)",speedActive:"rgba(224,136,152,.14)",inputBg:"rgba(255,255,255,.06)",inputBd:"rgba(255,255,255,.10)",overlayBg:"rgba(20,16,26,.98)",tabBg:"#1A1620",tabBd:"rgba(255,255,255,.06)",barFill:"#E08898",exBg:"rgba(80,168,184,.08)",exBd:"rgba(80,168,184,.12)",exTx:"#78C0D0",catCardBg:"rgba(255,255,255,.04)",catCardBd:"rgba(255,255,255,.06)",catCardShadow:"0 2px 12px rgba(0,0,0,.2)"};
const SPEEDS=[{key:"normal",label:"Normal",rate:.82,emoji:"🗣️"},{key:"slow",label:"Slow",rate:.15,emoji:"🐢"}];

function useSpeech(){const[s,ss]=useState(false);const[a,sa]=useState(null);const[v,sv]=useState(null);const r=useRef(null);useEffect(()=>{if(typeof window==="undefined"||!window.speechSynthesis)return;r.current=window.speechSynthesis;const p=()=>{const vs=r.current.getVoices();sv(vs.find(x=>x.lang==="hi-IN")||vs.find(x=>x.lang.startsWith("hi"))||null);};p();r.current.addEventListener("voiceschanged",p);return()=>r.current?.removeEventListener("voiceschanged",p);},[]);const speak=useCallback((t,rate=.82,k="normal")=>{if(!r.current)return;r.current.cancel();const u=new SpeechSynthesisUtterance(cleanForSpeech(t));u.lang="hi-IN";u.rate=rate;u.pitch=1;if(v)u.voice=v;u.onstart=()=>{ss(true);sa(k);};u.onend=()=>{ss(false);sa(null);};u.onerror=()=>{ss(false);sa(null);};r.current.speak(u);},[v]);const stop=useCallback(()=>{r.current?.cancel();ss(false);sa(null);},[]);return{speak,stop,speaking:s,activeSpeed:a,supported:typeof window!=="undefined"&&!!window.speechSynthesis};}
function useSwipe(onL,onR){const sx=useRef(0);const sy=useRef(0);return{onTouchStart:useCallback(e=>{sx.current=e.touches[0].clientX;sy.current=e.touches[0].clientY;},[]),onTouchEnd:useCallback(e=>{const dx=e.changedTouches[0].clientX-sx.current;const dy=e.changedTouches[0].clientY-sy.current;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5){dx>0?onR():onL();}},[onL,onR])};}

async function saveData(uid,d){try{await setDoc(doc(db,"users",uid),{...d,updatedAt:new Date().toISOString()},{merge:true});}catch(e){console.error(e);}}
async function loadData(uid){try{const s=await getDoc(doc(db,"users",uid));if(s.exists())return s.data();}catch(e){console.error(e);}return null;}

function PasswordInput({value,onChange,placeholder,onKeyDown,T}){const[v,setV]=useState(false);return(<div style={{position:"relative",width:"100%"}}><input type={v?"text":"password"} placeholder={placeholder} value={value} onChange={onChange} onKeyDown={onKeyDown} style={{width:"100%",padding:"14px 48px 14px 16px",borderRadius:14,border:`1.5px solid ${T.inputBd}`,background:T.inputBg,color:T.text,fontSize:16,fontFamily:"'Outfit',sans-serif",outline:"none",boxSizing:"border-box"}}/><button type="button" onClick={()=>setV(x=>!x)} tabIndex={-1} style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)",background:"none",border:"none",cursor:"pointer",padding:"6px",color:T.muted,fontSize:16}}>{v?"🙈":"👁️"}</button></div>);}

const TUTORIAL=[{e:"👋",t:"Welcome!",b:"Learn Hindi with flashcards, audio & spaced repetition."},{e:"📚",t:"Flip & Swipe",b:"Tap to flip. Swipe right = got it, left = still learning."},{e:"💡",t:"Hints",b:"Tap '💡 Hint' for a clue — first letter, letter count, sound-alikes."},{e:"🏆",t:"5 Levels",b:"Correct → level up, wrong → level down. Higher levels repeat less."},{e:"🗣️",t:"Audio",b:"Normal & Slow speed. Example sentences with audio too."},{e:"🌐",t:"Deutsch?",b:"Switch to German in Settings. Every card has 🇩🇪 memory tricks."},{e:"🚀",t:"Ready!",b:"Pick a category and start — बहुत मज़ा आएगा!"}];
function TutorialModal({T,onDone}){const[s,setS]=useState(0);const t=TUTORIAL[s];const last=s===TUTORIAL.length-1;return(<div style={{position:"fixed",inset:0,zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.5)",padding:20,boxSizing:"border-box"}}><div style={{background:T.overlayBg,borderRadius:28,padding:"32px 24px 24px",width:"100%",maxWidth:380,textAlign:"center",boxShadow:"0 20px 60px rgba(0,0,0,.2)",backdropFilter:"blur(20px)"}}><div style={{fontSize:48,marginBottom:8}}>{t.e}</div><h2 style={{fontSize:22,fontWeight:800,color:T.text,margin:"0 0 8px"}}>{t.t}</h2><p style={{fontSize:15,color:T.sub,lineHeight:1.6,margin:"0 0 20px"}}>{t.b}</p><div style={{display:"flex",gap:4,justifyContent:"center",marginBottom:16}}>{TUTORIAL.map((_,i)=>(<div key={i} style={{width:i===s?18:8,height:5,borderRadius:3,background:i===s?T.accent:`${T.accent}30`,transition:"all .3s"}}/>))}</div><div style={{display:"flex",gap:10}}>{s>0&&<button onClick={()=>setS(s=>s-1)} style={{flex:1,padding:"12px",borderRadius:14,border:`1.5px solid ${T.pillBd}`,background:T.btnBg,color:T.sub,fontSize:15,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>←</button>}<button onClick={()=>last?onDone():setS(s=>s+1)} style={{flex:1,padding:"12px",borderRadius:14,border:"none",background:`linear-gradient(135deg,${T.accent},${T.accent}DD)`,color:"#FFF",fontSize:15,fontFamily:"inherit",fontWeight:700,cursor:"pointer"}}>{last?"Let's go!":"Next →"}</button></div><button onClick={onDone} style={{marginTop:8,background:"none",border:"none",color:T.muted,fontSize:13,fontFamily:"inherit",cursor:"pointer"}}>Skip</button></div></div>);}

function AuthScreen({T}){const[isS,setIsS]=useState(false);const[nm,setNm]=useState("");const[em,setEm]=useState("");const[pw,setPw]=useState("");const[err,setErr]=useState("");const[ld,setLd]=useState(false);const sub=async()=>{setErr("");if(isS&&!nm.trim()){setErr("Enter your name");return;}if(!em||!pw){setErr("Fill all fields");return;}if(pw.length<6){setErr("Min 6 chars");return;}setLd(true);try{if(isS){const c=await createUserWithEmailAndPassword(auth,em,pw);await setDoc(doc(db,"users",c.user.uid),{name:nm.trim(),cardLevels:{},stats:{totalMinutes:0,dailyLog:{},dailyTarget:25},lang:"en",showTutorial:true});}else await signInWithEmailAndPassword(auth,em,pw);}catch(e){setErr(e.code==="auth/invalid-credential"?"Invalid email/password.":e.code==="auth/email-already-in-use"?"Already registered.":e.message);}setLd(false);};const iS={width:"100%",padding:"14px 16px",borderRadius:14,border:`1.5px solid ${T.inputBd}`,background:T.inputBg,color:T.text,fontSize:16,fontFamily:"'Outfit',sans-serif",outline:"none",boxSizing:"border-box"};
return(<div style={{minHeight:"100vh",background:T.bgGrad,fontFamily:"'Outfit',sans-serif",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"24px 20px",boxSizing:"border-box"}}><link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Noto+Sans+Devanagari:wght@400;500;600;700&display=swap" rel="stylesheet"/><div style={{width:"100%",maxWidth:400,textAlign:"center"}}><div style={{fontSize:15,letterSpacing:3,color:T.accent,fontWeight:700,marginBottom:6,fontFamily:"'Noto Sans Devanagari',sans-serif"}}>हिन्दी सीखें</div><h1 style={{fontSize:34,fontWeight:800,margin:0,color:T.text}}>Hindi Flashcards</h1><p style={{fontSize:15,color:T.sub,margin:"8px 0 28px"}}>{isS?"Create account":"Log in"}</p><div style={{display:"flex",flexDirection:"column",gap:12}}>{isS&&<input placeholder="Your name" value={nm} onChange={e=>setNm(e.target.value)} style={iS}/>}<input type="email" placeholder="Email" value={em} onChange={e=>setEm(e.target.value)} style={iS}/><PasswordInput value={pw} onChange={e=>setPw(e.target.value)} placeholder="Password (min 6)" onKeyDown={e=>e.key==="Enter"&&sub()} T={T}/>{err&&<div style={{padding:"10px",borderRadius:12,background:"#E8505014",border:"1px solid #E8505030",color:"#C03040",fontSize:13,textAlign:"left"}}>{err}</div>}<button onClick={sub} disabled={ld} style={{padding:"15px",borderRadius:16,border:"none",background:`linear-gradient(135deg,${T.accent},${T.accent}CC)`,color:"#FFF",fontSize:17,fontFamily:"inherit",fontWeight:700,cursor:ld?"wait":"pointer",opacity:ld?.7:1}}>{ld?"...":isS?"Create Account":"Log In"}</button><button onClick={()=>{setIsS(s=>!s);setErr("");}} style={{padding:"10px",borderRadius:12,border:`1px solid ${T.pillBd}`,background:"transparent",color:T.sub,fontSize:14,fontFamily:"inherit",cursor:"pointer"}}>{isS?"Have account? Log in":"New? Sign up"}</button></div></div></div>);}

function getLevel(cl,id){return cl[id]||{level:1,lastCorrect:null};}
function isDue(cl,id){const c=getLevel(cl,id);if(!c.lastCorrect||c.level<=1)return true;return Date.now()-new Date(c.lastCorrect).getTime()>=LVL_D[Math.min(c.level-1,4)];}
function lvlUp(cl,id){const c=getLevel(cl,id);return{...cl,[id]:{level:Math.min(c.level+1,5),lastCorrect:new Date().toISOString()}};}
function lvlDown(cl,id){const c=getLevel(cl,id);return{...cl,[id]:{level:Math.max(c.level-1,1),lastCorrect:c.lastCorrect}};}
function shuffleArr(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;}

function NamasteAnim({name,T}){const[p,setP]=useState(0);useEffect(()=>{const t1=setTimeout(()=>setP(1),600);const t2=setTimeout(()=>setP(2),1800);const t3=setTimeout(()=>setP(3),2800);return()=>{clearTimeout(t1);clearTimeout(t2);clearTimeout(t3);};},[]);if(p===3)return null;return(<div style={{position:"fixed",inset:0,zIndex:150,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.3)",backdropFilter:"blur(8px)"}}><div style={{textAlign:"center"}}><div style={{fontSize:72,transition:"all .4s",transform:p===1?"scale(1.2)":"scale(1)"}}>{"👋🙏👋"[p]||"👋"}</div><div style={{fontSize:28,fontWeight:800,color:"#FFF",marginTop:12,textShadow:"0 2px 20px rgba(0,0,0,.3)"}}>Namaste, {name}!</div></div></div>);}

export default function App(){
  const[user,setUser]=useState(null);const[userName,setUserName]=useState("");const[authLoading,setAuthLoading]=useState(true);
  const[activeCategory,setActiveCategory]=useState(null);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[cardLevels,setCardLevels]=useState({});const[anim,setAnim]=useState(false);const[dark,setDark]=useState(false);
  const[autoSpeak,setAutoSpeak]=useState(true);const[saving,setSaving]=useState(false);
  const[tab,setTab]=useState("practice");const[showList,setShowList]=useState(null);
  const[swipeHint,setSwipeHint]=useState(null);const[practiceMode,setPracticeMode]=useState(null);
  const[stats,setStats]=useState({totalMinutes:0,dailyLog:{},dailyTarget:25});
  const[showHint,setShowHint]=useState(false);const[todayFlips,setTodayFlips]=useState(0);
  const[showTutorial,setShowTutorial]=useState(false);const[lang,setLang]=useState("en");
  const[shuffled,setShuffled]=useState(false);const[shuffledCards,setShuffledCards]=useState([]);
  const[showNamaste,setShowNamaste]=useState(false);
  const lastActivity=useRef(Date.now());const sessionStart=useRef(Date.now());

  const{speak,stop,speaking,activeSpeed,supported}=useSpeech();
  const T=dark?TD:TL;const u=UI[lang]||UI.en;const today=new Date().toISOString().slice(0,10);
  const lvlNames=[u.new,u.reviewing,u.improving,u.strong,u.master];

  const knownSet=useMemo(()=>new Set(Object.entries(cardLevels).filter(([,v])=>v.level>=5).map(([k])=>+k)),[cardLevels]);
  const learningSet=useMemo(()=>new Set(Object.entries(cardLevels).filter(([,v])=>v.level>=2&&v.level<5).map(([k])=>+k)),[cardLevels]);
  const dueCards=useMemo(()=>ALL_CARDS.filter(c=>isDue(cardLevels,c.id)),[cardLevels]);

  const baseCards=useMemo(()=>{
    if(practiceMode==="learning")return ALL_CARDS.filter(c=>{const l=getLevel(cardLevels,c.id).level;return l>=2&&l<5&&isDue(cardLevels,c.id);});
    if(practiceMode==="due")return dueCards;
    if(activeCategory==="All")return ALL_CARDS;
    if(activeCategory)return ALL_CARDS.filter(c=>c.cat===activeCategory);
    return[];
  },[activeCategory,practiceMode,cardLevels,dueCards]);

  const cards=shuffled?shuffledCards:baseCards;
  const card=cards[idx]||cards[0];const color=CC[card?.cat]||"#C06080";
  const catName=c=>lang==="de"?(CAT_DE[c]||c):c;
  const cardFront=lang==="de"?(card?.frontDe||card?.front):card?.front;
  const cardHint=lang==="de"?(card?.hintDe||card?.hint):card?.hint;
  const exLang=lang==="de"?(card?.example?.de||card?.example?.en):card?.example?.en;
  const markActive=useCallback(()=>{lastActivity.current=Date.now();},[]);

  // Clamp idx when cards change (prevents skip bug in filtered modes)
  useEffect(()=>{if(cards.length>0&&idx>=cards.length)setIdx(Math.max(0,cards.length-1));},[cards.length,idx]);

  useEffect(()=>{const unsub=onAuthStateChanged(auth,async usr=>{setUser(usr);if(usr){const d=await loadData(usr.uid);if(d){setCardLevels(d.cardLevels||{});setUserName(d.name||"");setStats(d.stats||{totalMinutes:0,dailyLog:{},dailyTarget:25});setTodayFlips(d.stats?.dailyLog?.[today]||0);setLang(d.lang||"en");if(d.showTutorial)setShowTutorial(true);}setShowNamaste(true);}setAuthLoading(false);});return()=>unsub();},[]);

  useEffect(()=>{if(!user)return;const iv=setInterval(()=>{if(Date.now()-lastActivity.current<60000){const el=(Date.now()-sessionStart.current)/60000;if(el>0&&el<2)setStats(p=>({...p,totalMinutes:(p.totalMinutes||0)+el}));}sessionStart.current=Date.now();},30000);return()=>clearInterval(iv);},[user]);

  const saveTimeout=useRef(null);
  useEffect(()=>{if(!user)return;if(saveTimeout.current)clearTimeout(saveTimeout.current);saveTimeout.current=setTimeout(async()=>{setSaving(true);await saveData(user.uid,{name:userName,cardLevels,stats,lang,showTutorial:false});setSaving(false);},1000);return()=>{if(saveTimeout.current)clearTimeout(saveTimeout.current);};},[cardLevels,user,userName,stats,lang]);

  const prevFlipped=useRef(false);
  useEffect(()=>{if(flipped&&!prevFlipped.current){setTodayFlips(f=>f+1);setStats(p=>({...p,dailyLog:{...p.dailyLog,[today]:(p.dailyLog?.[today]||0)+1}}));if(autoSpeak&&supported&&card)setTimeout(()=>speak(card.back,.82,"normal"),400);}prevFlipped.current=flipped;},[flipped,card,autoSpeak,supported,speak,today]);

  const doFlip=useCallback(()=>{if(!anim){setFlipped(f=>!f);setShowHint(false);markActive();}},[anim,markActive]);
  const nav=useCallback(d=>{if(anim)return;setAnim(true);setFlipped(false);setShowHint(false);stop();markActive();setTimeout(()=>{setIdx(i=>{const n=i+d;return n<0?cards.length-1:n>=cards.length?0:n;});setAnim(false);},200);},[cards.length,anim,stop,markActive]);

  // FIX: In filtered practice modes, don't nav(1) — the card will be removed from the filtered list,
  // so the current index naturally points to the next card.
  const markKnow=useCallback(()=>{if(!card)return;markActive();setCardLevels(p=>lvlUp(p,card.id));if(practiceMode){setFlipped(false);setShowHint(false);stop();}else{nav(1);}},[card,nav,markActive,practiceMode,stop]);
  const markLearn=useCallback(()=>{if(!card)return;markActive();setCardLevels(p=>lvlDown(p,card.id));if(practiceMode){setFlipped(false);setShowHint(false);stop();}else{nav(1);}},[card,nav,markActive,practiceMode,stop]);

  const onSwipeL=useCallback(()=>{setSwipeHint("left");setTimeout(()=>setSwipeHint(null),400);markLearn();},[markLearn]);
  const onSwipeR=useCallback(()=>{setSwipeHint("right");setTimeout(()=>setSwipeHint(null),400);markKnow();},[markKnow]);
  const swipe=useSwipe(onSwipeL,onSwipeR);
  const handleLogout=async()=>{stop();await signOut(auth);};
  const pct=Math.round((knownSet.size/ALL_CARDS.length)*100);
  const handlePlay=(e,sp)=>{e.stopPropagation();markActive();if(speaking&&activeSpeed===sp.key){stop();return;}speak(card.back,sp.rate,sp.key);};
  const displayName=userName||user?.email?.split("@")[0]||"Learner";
  const jumpToCard=id=>{setPracticeMode(null);setActiveCategory("All");setShuffled(false);setFlipped(false);setShowHint(false);stop();const i=ALL_CARDS.findIndex(c=>c.id===id);if(i>=0)setIdx(i);setShowList(null);setTab("practice");};
  const exitPractice=()=>{setPracticeMode(null);setActiveCategory(null);setShuffled(false);setIdx(0);setFlipped(false);setShowHint(false);};
  const goBackToGrid=()=>{setActiveCategory(null);setShuffled(false);setIdx(0);setFlipped(false);setShowHint(false);stop();};
  const enterCategory=cat=>{setActiveCategory(cat);setIdx(0);setFlipped(false);setShowHint(false);setShuffled(false);};
  const doShuffle=()=>{setShuffledCards(shuffleArr(baseCards));setShuffled(true);setIdx(0);setFlipped(false);};
  const dailyTarget=stats.dailyTarget||25;const targetPct=Math.min(Math.round((todayFlips/dailyTarget)*100),100);
  const cl=card?getLevel(cardLevels,card.id):{level:1};
  const speakEx=e=>{e.stopPropagation();markActive();if(card?.example)speak(card.example.hi,.4,"normal");};
  const closeTutorial=()=>{setShowTutorial(false);if(user)saveData(user.uid,{showTutorial:false});};
  const inCardView=activeCategory!==null||practiceMode;

  if(authLoading)return(<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:T.bgGrad,fontFamily:"'Outfit',sans-serif"}}><link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Noto+Sans+Devanagari:wght@400;500;600;700&display=swap" rel="stylesheet"/><div style={{textAlign:"center",color:T.muted}}><div style={{fontSize:40,marginBottom:12}}>🇮🇳</div><div style={{fontSize:18,fontWeight:600}}>Loading...</div></div></div>);
  if(!user)return<AuthScreen T={T}/>;

  return(
    <div style={{minHeight:"100vh",background:T.bgGrad,fontFamily:"'Outfit',sans-serif",color:T.text,display:"flex",flexDirection:"column",alignItems:"center",padding:"14px 14px 80px",boxSizing:"border-box",transition:"background .4s"}}>
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Noto+Sans+Devanagari:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      <style>{`@keyframes speakPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}@keyframes barBounce{0%,100%{transform:scaleY(.3)}50%{transform:scaleY(1)}}@keyframes shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}@keyframes swL{0%{opacity:0;transform:translateX(20px)}50%{opacity:1}100%{opacity:0;transform:translateX(-20px)}}@keyframes swR{0%{opacity:0;transform:translateX(-20px)}50%{opacity:1}100%{opacity:0;transform:translateX(20px)}}@keyframes hintIn{from{opacity:0;max-height:0}to{opacity:1;max-height:200px}}.cat-scroll::-webkit-scrollbar{display:none}*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;margin:0;padding:0}`}</style>

      {showNamaste&&<NamasteAnim name={displayName} T={T}/>}
      {showTutorial&&<TutorialModal T={T} onDone={closeTutorial}/>}

      {/* List modals */}
      {showList&&<div style={{position:"fixed",inset:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.4)",padding:20}} onClick={()=>setShowList(null)}><div onClick={e=>e.stopPropagation()} style={{background:T.overlayBg,borderRadius:24,padding:"24px 20px",width:"100%",maxWidth:440,maxHeight:"85vh",overflowY:"auto",boxShadow:"0 20px 60px rgba(0,0,0,.2)",backdropFilter:"blur(20px)"}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>
          <h2 style={{fontSize:20,fontWeight:800,color:T.text,margin:0}}>{showList==="known"?`⭐ ${u.mastered}`:`📖 ${u.learning}`} ({(showList==="known"?knownSet:learningSet).size})</h2>
          <button onClick={()=>setShowList(null)} style={{width:34,height:34,borderRadius:"50%",border:`1px solid ${T.pillBd}`,background:T.btnBg,color:T.btnTx,cursor:"pointer",fontSize:16,display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button>
        </div>
        {showList==="learning"&&learningSet.size>0&&<button onClick={()=>{setPracticeMode("learning");setIdx(0);setFlipped(false);setShowList(null);setTab("practice");}} style={{width:"100%",padding:"11px",borderRadius:14,border:"1.5px solid #C8A04044",background:"#C8A04012",color:"#C8A040",fontSize:14,fontFamily:"inherit",fontWeight:700,cursor:"pointer",marginBottom:12}}>🎯 {u.pracAll}</button>}
        {ALL_CARDS.filter(c=>(showList==="known"?knownSet:learningSet).has(c.id)).map(c=>{const lv=getLevel(cardLevels,c.id);const front=lang==="de"?(c.frontDe||c.front):c.front;return(<button key={c.id} onClick={()=>jumpToCard(c.id)} style={{width:"100%",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"11px 14px",borderRadius:14,border:`1px solid ${T.pillBd}`,background:T.pillBg,marginBottom:6,cursor:"pointer",textAlign:"left",fontFamily:"inherit"}}><div><div style={{fontSize:15,fontWeight:700,color:T.text}}>{front}</div><div style={{fontSize:13,color:CC[c.cat],fontWeight:600,marginTop:1}}>{c.back} · {c.tl}</div></div><span style={{fontSize:10,fontWeight:700,color:LVL_C[lv.level-1],background:`${LVL_C[lv.level-1]}15`,padding:"2px 7px",borderRadius:6}}>Lv{lv.level}</span></button>);})}
        {(showList==="known"?knownSet:learningSet).size===0&&<div style={{textAlign:"center",padding:"40px 0",color:T.muted}}>—</div>}
      </div></div>}

      <div style={{position:"relative",zIndex:1,width:"100%",maxWidth:560}}>

        {tab==="practice"&&<>
          <div style={{marginBottom:10}}><div style={{fontSize:12,letterSpacing:3,color:T.accent,fontWeight:700,marginBottom:2,fontFamily:"'Noto Sans Devanagari',sans-serif"}}>हिन्दी सीखें</div><h1 style={{fontSize:22,fontWeight:800,margin:0,color:T.text}}>Namaste, {displayName}!</h1></div>
          <div style={{marginBottom:10,padding:"10px 14px",borderRadius:14,background:T.pillBg,border:`1px solid ${T.pillBd}`,boxShadow:T.catCardShadow}}>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:4}}><span style={{fontWeight:600,color:T.text}}>🎯 {todayFlips}/{dailyTarget} {u.flips}</span><span style={{fontWeight:700,color:targetPct>=100?"#40A050":T.accent}}>{targetPct>=100?u.done:`${targetPct}%`}</span></div>
            <div style={{height:5,borderRadius:3,background:T.dotBg,overflow:"hidden"}}><div style={{height:"100%",borderRadius:3,width:`${targetPct}%`,background:targetPct>=100?"linear-gradient(90deg,#40A050,#80B050)":"linear-gradient(90deg,#D06060,#C8A040)",transition:"width .4s"}}/></div>
          </div>
          {practiceMode&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 14px",borderRadius:12,background:"#C8A04014",border:"1.5px solid #C8A04030",marginBottom:8}}><span style={{fontSize:13,fontWeight:700,color:"#C8A040"}}>🎯 {practiceMode==="learning"?u.pracLearn:u.pracDue}: {cards.length}</span><button onClick={exitPractice} style={{padding:"5px 10px",borderRadius:10,border:"1px solid #C8A04040",background:"transparent",color:"#C8A040",fontSize:11,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>{u.exit}</button></div>}

          {/* CATEGORY GRID */}
          {!inCardView&&<>
            <div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:10,marginBottom:14}}>
              {CATEGORIES.filter(c=>c!=="All").map(cat=>{const cc=CC[cat]||T.accent;const catCards=ALL_CARDS.filter(c=>c.cat===cat);const mastered=catCards.filter(c=>getLevel(cardLevels,c.id).level>=5).length;const due=catCards.filter(c=>isDue(cardLevels,c.id)).length;const pctCat=catCards.length?Math.round((mastered/catCards.length)*100):0;return(<button key={cat} onClick={()=>enterCategory(cat)} style={{padding:"16px 14px",borderRadius:18,border:`1px solid ${T.catCardBd}`,background:T.catCardBg,boxShadow:T.catCardShadow,cursor:"pointer",textAlign:"left",fontFamily:"inherit",display:"flex",flexDirection:"column",gap:6,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,right:0,height:3,background:cc,borderRadius:"18px 18px 0 0"}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:22}}>{CAT_EMOJI[cat]||"📁"}</span><span style={{fontSize:10,fontWeight:600,color:T.muted}}>{catCards.length}</span></div><div style={{fontSize:15,fontWeight:700,color:T.text}}>{catName(cat)}</div><div style={{height:4,borderRadius:2,background:T.dotBg,overflow:"hidden"}}><div style={{height:"100%",borderRadius:2,width:`${pctCat}%`,background:cc}}/></div><div style={{display:"flex",justifyContent:"space-between",fontSize:11,color:T.muted}}><span>{mastered}/{catCards.length} ⭐</span>{due>0&&<span style={{color:"#D06060",fontWeight:600}}>{due} {u.dueNow}</span>}</div></button>);})}
            </div>
            <div style={{display:"flex",gap:8,marginBottom:14}}>
              <button onClick={()=>enterCategory("All")} style={{flex:1,padding:"12px",borderRadius:14,border:`1px solid ${T.pillBd}`,background:T.pillBg,color:T.text,fontSize:14,fontFamily:"inherit",fontWeight:700,cursor:"pointer",boxShadow:T.catCardShadow}}>📚 {u.browseAll} ({ALL_CARDS.length})</button>
              {dueCards.length>0&&<button onClick={()=>{setPracticeMode("due");setIdx(0);}} style={{flex:1,padding:"12px",borderRadius:14,border:"1.5px solid #D0606030",background:"#D0606010",color:"#D06060",fontSize:14,fontFamily:"inherit",fontWeight:700,cursor:"pointer"}}>🔥 {dueCards.length} {u.due}</button>}
            </div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,padding:"10px 0",borderTop:`1px solid ${T.divider}`}}>
              {[{l:u.mastered,v:knownSet.size,c:"#40A050",cl:()=>setShowList("known")},{l:u.learning,v:learningSet.size,c:"#C8A040",cl:()=>setShowList("learning")},{l:u.due,v:dueCards.length,c:"#D06060",cl:()=>{setPracticeMode("due");setIdx(0);}}].map(s=>(<div key={s.l} onClick={s.cl} style={{textAlign:"center",padding:"8px 4px",borderRadius:12,background:T.pillBg,border:`1px solid ${T.pillBd}`,cursor:"pointer",boxShadow:T.catCardShadow}}><div style={{fontSize:20,fontWeight:800,color:s.c}}>{s.v}</div><div style={{fontSize:10,color:T.muted,fontWeight:600,textTransform:"uppercase"}}>{s.l}</div></div>))}
            </div>
          </>}

          {/* CARD VIEW */}
          {inCardView&&cards.length>0&&<>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}>
              <button onClick={practiceMode?exitPractice:goBackToGrid} style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:12,border:`1px solid ${T.pillBd}`,background:T.pillBg,color:T.sub,fontSize:13,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>← {u.back}</button>
              <div style={{display:"flex",alignItems:"center",gap:6}}>
                <span style={{fontSize:13,color,fontWeight:700}}>{!practiceMode&&activeCategory!=="All"?catName(activeCategory)+" · ":""}{idx+1}/{cards.length}</span>
                <button onClick={doShuffle} style={{padding:"5px 10px",borderRadius:10,border:`1px solid ${T.pillBd}`,background:shuffled?`${T.accent}14`:T.pillBg,color:shuffled?T.accent:T.muted,fontSize:11,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>🔀 {u.shuffle}</button>
              </div>
            </div>
            <div style={{display:"flex",alignItems:"center",gap:6,marginBottom:6,padding:"0 2px"}}>
              <div style={{display:"flex",gap:3}}>{[1,2,3,4,5].map(l=>(<div key={l} style={{width:8,height:8,borderRadius:"50%",background:cl.level>=l?LVL_C[l-1]:T.dotBg}}/>))}</div>
              <span style={{fontSize:12,fontWeight:700,color:LVL_C[cl.level-1]}}>{lvlNames[cl.level-1]}</span>
            </div>

            {/* FLASHCARD */}
            <div {...swipe} onClick={doFlip} style={{perspective:1200,cursor:"pointer",marginBottom:8,height:450,position:"relative"}}>
              {swipeHint==="right"&&<div style={{position:"absolute",inset:0,zIndex:10,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:24,background:"rgba(64,160,80,.12)",animation:"swR .4s ease-out forwards",pointerEvents:"none"}}><span style={{fontSize:44}}>✅</span></div>}
              {swipeHint==="left"&&<div style={{position:"absolute",inset:0,zIndex:10,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:24,background:"rgba(200,160,64,.12)",animation:"swL .4s ease-out forwards",pointerEvents:"none"}}><span style={{fontSize:44}}>🔄</span></div>}
              <div style={{position:"relative",width:"100%",height:"100%",transformStyle:"preserve-3d",transform:flipped?"rotateY(180deg)":"rotateY(0)",transition:"transform .65s cubic-bezier(.23,1,.32,1)"}}>
                <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",WebkitBackfaceVisibility:"hidden",borderRadius:24,background:T.cardFront,border:`1px solid ${color}18`,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"28px 22px",boxShadow:T.cardShadow}}>
                  <div style={{position:"absolute",top:14,right:16,fontSize:12,color:T.muted,letterSpacing:1.5,textTransform:"uppercase",fontWeight:600}}>{lang==="de"?"Deutsch":"English"}</div>
                  <div style={{fontSize:cardFront&&cardFront.length>20?26:42,fontWeight:800,textAlign:"center",lineHeight:1.25,color:T.text}}>{cardFront}</div>
                  <div style={{marginTop:14,width:"100%",maxWidth:360,textAlign:"center"}}>
                    {!showHint?<button onClick={e=>{e.stopPropagation();setShowHint(true);markActive();}} style={{padding:"8px 18px",borderRadius:14,border:`1.5px solid ${T.hintBd}`,background:T.hintBg,color:T.hintTx,fontSize:14,fontFamily:"inherit",fontWeight:600,cursor:"pointer",margin:"0 auto",display:"flex",alignItems:"center",gap:6}}>💡 {u.hint}</button>
                    :<div style={{animation:"hintIn .3s ease-out",padding:"10px 16px",borderRadius:14,background:T.hintBg,border:`1.5px solid ${T.hintBd}`,fontSize:14,color:T.hintTx,lineHeight:1.5,fontWeight:500}} onClick={e=>e.stopPropagation()}>{cardHint}</div>}
                  </div>
                  <div style={{marginTop:14,fontSize:13,color:T.faint}}>{u.flipHint}</div>
                </div>
                <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",WebkitBackfaceVisibility:"hidden",transform:"rotateY(180deg)",borderRadius:24,background:dark?`linear-gradient(155deg,${color}10,#1A1620 25%,#161420)`:`linear-gradient(155deg,${color}06,#FFF 25%,#F8F6F3)`,border:`1px solid ${color}${dark?"28":"14"}`,display:"flex",flexDirection:"column",alignItems:"center",padding:"12px 14px",boxShadow:T.cardShadow,overflowY:"auto",justifyContent:"flex-start",paddingTop:32}}>
                  <div style={{position:"absolute",top:10,right:14,fontSize:11,color,letterSpacing:1.5,textTransform:"uppercase",fontWeight:700,opacity:.7,fontFamily:"'Noto Sans Devanagari',sans-serif"}}>हिन्दी</div>
                  <div style={{fontFamily:"'Noto Sans Devanagari',sans-serif",fontSize:card?.back.length>14?28:46,fontWeight:700,textAlign:"center",color:T.text,lineHeight:1.3,whiteSpace:"pre-line"}}>{card?.back}</div>
                  <div style={{marginTop:2,fontSize:17,fontWeight:600,color}}>{card?.tl}</div>
                  {supported&&<div onClick={e=>e.stopPropagation()} style={{marginTop:8,padding:"4px",borderRadius:14,background:T.speedBg,border:`1px solid ${T.speedBd}`,display:"flex",gap:4,width:"100%",maxWidth:400}}>
                    {SPEEDS.map(sp=>{const isA=speaking&&activeSpeed===sp.key;return(<button key={sp.key} onClick={e=>handlePlay(e,sp)} style={{flex:1,padding:"8px",borderRadius:10,border:"1.5px solid",borderColor:isA?`${color}60`:"transparent",background:isA?T.speedActive:"transparent",color:isA?color:T.sub,cursor:"pointer",fontSize:14,fontFamily:"inherit",fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center",gap:4,animation:isA?"speakPulse 1.2s ease-in-out infinite":"none"}}>{isA?<div style={{display:"flex",gap:2,height:14}}>{[0,1,2,3].map(b=><div key={b} style={{width:3,height:14,borderRadius:2,background:color,animation:`barBounce 0.${5+b*2}s ease-in-out infinite`,animationDelay:`${b*.1}s`}}/>)}</div>:<span>{sp.emoji}</span>}{sp.label}</button>);})}
                  </div>}
                  <div style={{marginTop:6,padding:"5px 12px",borderRadius:10,background:T.pronBg,border:`1px solid ${T.pronBd}`,fontSize:14,color,fontWeight:500,width:"100%",maxWidth:400,textAlign:"center"}}>📢 {card?.pron}</div>
                  <div style={{marginTop:5,padding:"6px 12px",borderRadius:10,background:T.trickBg,border:`1px solid ${T.trickBd}`,fontSize:13,color:T.trickTx,lineHeight:1.5,textAlign:"center",width:"100%",maxWidth:400,fontWeight:500}}>🇩🇪 {card?.trick}</div>
                  {card?.example&&<div onClick={e=>e.stopPropagation()} style={{marginTop:5,padding:"8px 12px",borderRadius:10,background:T.exBg,border:`1px solid ${T.exBd}`,width:"100%",maxWidth:400}}>
                    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:11,fontWeight:700,color:T.exTx}}>{u.example}</span>{supported&&<button onClick={speakEx} style={{padding:"3px 8px",borderRadius:8,border:`1px solid ${T.exBd}`,background:"transparent",color:T.exTx,fontSize:11,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>{u.play}</button>}</div>
                    <div style={{fontFamily:"'Noto Sans Devanagari',sans-serif",fontSize:15,fontWeight:600,color:T.text,lineHeight:1.4}}>{card.example.hi}</div>
                    <div style={{fontSize:12,color:T.exTx,marginTop:1}}>{card.example.tl}</div>
                    <div style={{fontSize:12,color:T.muted,marginTop:1}}>{exLang}</div>
                  </div>}
                </div>
              </div>
            </div>
            <div style={{display:"flex",gap:8,justifyContent:"center",alignItems:"center",marginBottom:10}}>
              <button onClick={()=>nav(-1)} style={{width:52,height:52,borderRadius:"50%",border:`2px solid ${T.btnBd}`,background:T.btnBg,color:T.text,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,fontWeight:700,fontFamily:"inherit",boxShadow:T.catCardShadow}}>‹</button>
              <button onClick={markLearn} style={{padding:"12px 18px",borderRadius:16,border:`2px solid #C8A04040`,background:"#C8A04010",color:"#C8A040",cursor:"pointer",fontSize:14,fontFamily:"inherit",fontWeight:700}}>{u.still}</button>
              <button onClick={markKnow} style={{padding:"12px 18px",borderRadius:16,border:`2px solid #40A05040`,background:"#40A05010",color:"#40A050",cursor:"pointer",fontSize:14,fontFamily:"inherit",fontWeight:700}}>{u.gotIt}</button>
              <button onClick={()=>nav(1)} style={{width:52,height:52,borderRadius:"50%",border:`2px solid ${T.btnBd}`,background:T.btnBg,color:T.text,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,fontWeight:700,fontFamily:"inherit",boxShadow:T.catCardShadow}}>›</button>
            </div>
          </>}
          {inCardView&&cards.length===0&&<div style={{textAlign:"center",padding:"60px 20px",color:T.muted}}><div style={{fontSize:40,marginBottom:12}}>🎉</div><div style={{fontSize:18,fontWeight:600}}>{u.allDone}</div><button onClick={exitPractice} style={{marginTop:16,padding:"12px 24px",borderRadius:16,border:`1.5px solid ${T.accent}40`,background:`${T.accent}10`,color:T.accent,fontSize:15,fontFamily:"inherit",fontWeight:700,cursor:"pointer"}}>{u.back}</button></div>}
        </>}

        {tab==="progress"&&<div>
          <h2 style={{fontSize:24,fontWeight:800,color:T.text,margin:"0 0 14px"}}>📊 {u.progress}</h2>
          <div style={{display:"flex",alignItems:"center",gap:18,padding:"18px 16px",borderRadius:20,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:14,boxShadow:T.catCardShadow}}>
            <div style={{position:"relative",width:80,height:80,flexShrink:0}}><svg width="80" height="80" viewBox="0 0 80 80"><circle cx="40" cy="40" r="34" fill="none" stroke={T.dotBg} strokeWidth="7"/><circle cx="40" cy="40" r="34" fill="none" stroke={T.accent} strokeWidth="7" strokeDasharray={`${pct*2.14} ${214-pct*2.14}`} strokeDashoffset="54" strokeLinecap="round"/></svg><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,fontWeight:800,color:T.accent}}>{pct}%</div></div>
            <div><div style={{fontSize:13,fontWeight:600,color:T.muted,textTransform:"uppercase",letterSpacing:1,marginBottom:2}}>{u.mastery}</div><div style={{fontSize:18,fontWeight:700,color:T.text}}>✨ {knownSet.size}/{ALL_CARDS.length}</div><div style={{fontSize:13,color:T.sub,marginTop:3}}>⏱️ {Math.floor((stats.totalMinutes||0)/60)}h {Math.round((stats.totalMinutes||0)%60)}m</div><div style={{fontSize:13,color:T.sub,marginTop:2}}>🔥 {dueCards.length} {u.due.toLowerCase()}</div></div>
          </div>
          <div style={{padding:"14px",borderRadius:20,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:12,boxShadow:T.catCardShadow}}>
            <div style={{fontSize:15,fontWeight:700,color:T.text,marginBottom:10}}>📅 {u.week}</div>
            <div style={{display:"flex",gap:5,alignItems:"flex-end",height:80}}>
              {Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const k=d.toISOString().slice(0,10);const c=(stats.dailyLog||{})[k]||0;const isT=k===today;const max=Math.max(...Object.values(stats.dailyLog||{1:1}),dailyTarget,1);return(<div key={k} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:3}}><div style={{fontSize:10,fontWeight:700,color:isT?T.accent:T.muted}}>{c}</div><div style={{width:"100%",borderRadius:5,background:isT?T.accent:T.barFill,opacity:isT?1:.3,height:`${Math.max((c/max)*55,3)}px`,transition:"height .4s"}}/><div style={{fontSize:9,color:isT?T.accent:T.muted,fontWeight:isT?700:500}}>{d.toLocaleDateString(lang==="de"?"de":"en",{weekday:"short"})}</div></div>);})}
            </div>
          </div>
          <div style={{padding:"14px",borderRadius:20,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:12,boxShadow:T.catCardShadow}}>
            <div style={{fontSize:15,fontWeight:700,color:T.text,marginBottom:10}}>🏆 {u.levels}</div>
            {[1,2,3,4,5].map(lv=>{const ct=ALL_CARDS.filter(c=>{const l=getLevel(cardLevels,c.id).level;return lv===1?(l===1||!cardLevels[c.id]):l===lv;}).length;return(<div key={lv} style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><div style={{width:70,fontSize:12,fontWeight:700,color:LVL_C[lv-1]}}>{lvlNames[lv-1]}</div><div style={{flex:1,height:6,borderRadius:3,background:T.dotBg,overflow:"hidden"}}><div style={{height:"100%",borderRadius:3,width:`${(ct/ALL_CARDS.length)*100}%`,background:LVL_C[lv-1]}}/></div><div style={{width:24,fontSize:12,fontWeight:600,color:T.muted,textAlign:"right"}}>{ct}</div></div>);})}
          </div>
          <div style={{padding:"14px",borderRadius:20,background:T.pillBg,border:`1px solid ${T.pillBd}`,boxShadow:T.catCardShadow}}>
            <div style={{fontSize:15,fontWeight:700,color:T.text,marginBottom:10}}>📂 {u.cats}</div>
            {Object.entries(CC).map(([cat,col])=>{const cc=ALL_CARDS.filter(c=>c.cat===cat);const m=cc.filter(c=>getLevel(cardLevels,c.id).level>=5).length;const cp=cc.length?Math.round((m/cc.length)*100):0;return(<div key={cat} style={{marginBottom:7}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:3}}><span style={{fontSize:13,fontWeight:600,color:col}}>{catName(cat)}</span><span style={{fontSize:11,color:T.muted}}>{m}/{cc.length}</span></div><div style={{height:5,borderRadius:3,background:T.dotBg,overflow:"hidden"}}><div style={{height:"100%",borderRadius:3,width:`${cp}%`,background:col}}/></div></div>);})}
          </div>
        </div>}

        {tab==="settings"&&<div>
          <h2 style={{fontSize:24,fontWeight:800,color:T.text,margin:"0 0 16px"}}>⚙️ {u.settings}</h2>
          <p style={{fontSize:14,color:T.sub,margin:"0 0 16px"}}>{displayName} · {user.email}</p>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px",borderRadius:16,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:8,boxShadow:T.catCardShadow}}><span style={{fontSize:15,fontWeight:700,color:T.text}}>🌐 {u.lang}</span><div style={{display:"flex",gap:5}}>{[{k:"en",l:"English"},{k:"de",l:"Deutsch"}].map(o=>(<button key={o.k} onClick={()=>setLang(o.k)} style={{padding:"7px 12px",borderRadius:12,border:`1.5px solid ${lang===o.k?T.accent+"44":T.pillBd}`,background:lang===o.k?`${T.accent}14`:T.btnBg,color:lang===o.k?T.accent:T.text,fontSize:13,fontFamily:"inherit",fontWeight:lang===o.k?700:500,cursor:"pointer"}}>{o.l}</button>))}</div></div>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px",borderRadius:16,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:8,boxShadow:T.catCardShadow}}><span style={{fontSize:15,fontWeight:700,color:T.text}}>🌓 {u.theme}</span><button onClick={()=>setDark(d=>!d)} style={{padding:"7px 14px",borderRadius:12,border:`1.5px solid ${T.pillBd}`,background:T.btnBg,color:T.text,fontSize:13,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>{dark?"☀️ Light":"🌙 Dark"}</button></div>
          {supported&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px",borderRadius:16,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:8,boxShadow:T.catCardShadow}}><span style={{fontSize:15,fontWeight:700,color:T.text}}>🔊 {u.autoPlay}</span><button onClick={()=>setAutoSpeak(a=>!a)} style={{padding:"7px 14px",borderRadius:12,border:`1.5px solid ${autoSpeak?T.accent+"44":T.pillBd}`,background:autoSpeak?`${T.accent}14`:T.btnBg,color:autoSpeak?T.accent:T.text,fontSize:13,fontFamily:"inherit",fontWeight:600,cursor:"pointer"}}>{autoSpeak?"ON":"OFF"}</button></div>}
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px",borderRadius:16,background:T.pillBg,border:`1px solid ${T.pillBd}`,marginBottom:8,boxShadow:T.catCardShadow}}><div><div style={{fontSize:15,fontWeight:700,color:T.text}}>🎯 {u.target}</div><div style={{fontSize:12,color:T.muted}}>{dailyTarget}{u.perDay}</div></div><div style={{display:"flex",gap:5}}>{[15,25,40,60].map(n=>(<button key={n} onClick={()=>setStats(p=>({...p,dailyTarget:n}))} style={{padding:"6px 10px",borderRadius:10,border:`1.5px solid ${dailyTarget===n?T.accent+"44":T.pillBd}`,background:dailyTarget===n?`${T.accent}14`:"transparent",color:dailyTarget===n?T.accent:T.muted,fontSize:12,fontFamily:"inherit",fontWeight:700,cursor:"pointer"}}>{n}</button>))}</div></div>
          <button onClick={()=>setShowTutorial(true)} style={{width:"100%",padding:"14px",borderRadius:16,border:`1px solid ${T.pillBd}`,background:T.pillBg,color:T.text,fontSize:14,fontFamily:"inherit",fontWeight:600,cursor:"pointer",marginBottom:8,boxShadow:T.catCardShadow}}>📖 {u.replay}</button>
          <button onClick={handleLogout} style={{width:"100%",padding:"14px",borderRadius:16,border:`1px solid ${T.pillBd}`,background:T.pillBg,color:T.text,fontSize:15,fontFamily:"inherit",fontWeight:700,cursor:"pointer",marginBottom:16,boxShadow:T.catCardShadow}}>🚪 {u.logout}</button>
          <div style={{padding:"14px",borderRadius:16,border:"1.5px solid #D0606030",background:"#D0606008"}}><DeleteBtn T={T} u={u}/></div>
        </div>}
      </div>

      <div style={{position:"fixed",bottom:0,left:0,right:0,zIndex:50,background:T.tabBg,borderTop:`1px solid ${T.tabBd}`,display:"flex",justifyContent:"center",backdropFilter:"blur(16px)"}}>
        <div style={{display:"flex",maxWidth:560,width:"100%"}}>
          {[{k:"practice",i:"📚",l:u.practice},{k:"progress",i:"📊",l:u.progress},{k:"settings",i:"⚙️",l:u.settings}].map(t=>(<button key={t.k} onClick={()=>{setTab(t.k);if(t.k==="practice"&&!inCardView){setActiveCategory(null);setPracticeMode(null);}stop();}} style={{flex:1,padding:"10px 0 8px",border:"none",background:"transparent",cursor:"pointer",display:"flex",flexDirection:"column",alignItems:"center",gap:2,fontFamily:"inherit",color:tab===t.k?T.accent:T.muted}}>
            <span style={{fontSize:22}}>{t.i}</span><span style={{fontSize:11,fontWeight:tab===t.k?700:500}}>{t.l}</span>
            {tab===t.k&&<div style={{width:20,height:3,borderRadius:2,background:T.accent}}/>}
          </button>))}
        </div>
      </div>
    </div>
  );
}

function DeleteBtn({T,u}){const[cd,setCd]=useState(false);const[dp,setDp]=useState("");const[de,setDe]=useState("");const[dl,setDl]=useState(false);const hd=async()=>{if(!cd){setCd(true);return;}if(!dp){setDe(u.pw);return;}setDl(true);try{const c=EmailAuthProvider.credential(auth.currentUser.email,dp);await reauthenticateWithCredential(auth.currentUser,c);await deleteDoc(doc(db,"users",auth.currentUser.uid));await deleteUser(auth.currentUser);}catch(e){setDe("Wrong password.");setDl(false);}};
return(<><div style={{fontSize:14,fontWeight:700,color:"#C03040",marginBottom:4}}>⚠️ {u.deleteAcc}</div><div style={{fontSize:11,color:T.muted,marginBottom:8}}>{u.deleteWarn}</div>{cd&&<><PasswordInput value={dp} onChange={e=>setDp(e.target.value)} placeholder={u.pw} T={T} onKeyDown={e=>e.key==="Enter"&&hd()}/>{de&&<div style={{marginTop:6,fontSize:11,color:"#C03040"}}>{de}</div>}</>}<button onClick={hd} disabled={dl} style={{width:"100%",padding:"10px",borderRadius:12,border:"none",background:cd?"#C03040":"transparent",color:cd?"#FFF":"#C03040",fontSize:13,fontFamily:"'Outfit',sans-serif",fontWeight:700,cursor:dl?"wait":"pointer",marginTop:8,opacity:dl?.6:1}}>{dl?"...":cd?u.confirm:u.deleteAcc}</button>{cd&&<button onClick={()=>{setCd(false);setDe("");setDp("");}} style={{width:"100%",padding:"6px",border:"none",background:"transparent",color:T.muted,fontSize:12,fontFamily:"inherit",cursor:"pointer",marginTop:4}}>{u.cancel}</button>}</>);}
